Option Strict Off
Option Explicit On
Module AXHD
    ' { IP COMMAND LIST }
    ' PGM-1 Group Register
    Public Const IPxyRANGERead As Short = &H0S                          ' PGM-1 RANGE READ, 16bit, 0xFFFF
    Public Const IPxyRANGEWrite As Short = &H80S                        ' PGM-1 RANGE WRITE
    Public Const IPxySTDRead As Short = &H1S                            ' PGM-1 START/STOP SPEED DATA READ, 16bit, 
    Public Const IPxySTDWrite As Short = &H81S                          ' PGM-1 START/STOP SPEED DATA WRITE
    Public Const IPxyOBJRead As Short = &H2S                            ' PGM-1 OBJECT SPEED DATA READ, 16bit, 
    Public Const IPxyOBJWrite As Short = &H82S                          ' PGM-1 OBJECT SPEED DATA WRITE  
    Public Const IPxyRATE1Read As Short = &H3S                          ' PGM-1 RATE-1 DATA READ, 16bit, 0xFFFF
    Public Const IPxyRATE1Write As Short = &H83S                        ' PGM-1 RATE-1 DATA WRITE
    Public Const IPxyRATE2Read As Short = &H4S                          ' PGM-1 RATE-2 DATA READ, 16bit, 0xFFFF
    Public Const IPxyRATE2Write As Short = &H84S                        ' PGM-1 RATE-2 DATA WRITE
    Public Const IPxyRATE3Read As Short = &H5S                          ' PGM-1 RATE-3 DATA READ, 16bit, 0xFFFF
    Public Const IPxyRATE3Write As Short = &H85S                        ' PGM-1 RATE-3 DATA WRITE
    Public Const IPxyRCP12Read As Short = &H6S                          ' PGM-1 RATE CHANGE POINT 1-2 READ, 16bit, 0xFFFF
    Public Const IPxyRCP12Write As Short = &H86S                        ' PGM-1 RATE CHANGE POINT 1-2 WRITE
    Public Const IPxyRCP23Read As Short = &H7S                          ' PGM-1 RATE CHANGE POINT 2-3 READ, 16bit, 0xFFFF
    Public Const IPxyRCP23Write As Short = &H87S                        ' PGM-1 RATE CHANGE POINT 2-3 WRITE
    Public Const IPxySW1Read As Short = &H8S                            ' PGM-1 SW-1 DATA READ, 15bit, 0x7FFF
    Public Const IPxySW1Write As Short = &H88S                          ' PGM-1 SW-1 DATA WRITE
    Public Const IPxySW2Read As Short = &H9S                            ' PGM-1 SW-2 DATA READ, 15bit, 0x7FFF
    Public Const IPxySW2Write As Short = &H89S                          ' PGM-1 SW-2 DATA WRITE
    Public Const IPxyPWMRead As Short = &HAS                            ' PGM-1 PWM output configure DATA READ(0~6), 3bit, 0x00
    Public Const IPxyPWMWrite As Short = &H8AS                          ' PGM-1 PWM output configure DATA WRITE
    Public Const IPxyREARRead As Short = &HBS                           ' PGM-1 SLOW DOWN/REAR PULSE READ, 32bit, 0x00000000
    Public Const IPxyREARWrite As Short = &H8BS                         ' PGM-1 SLOW DOWN/REAR PULSE WRITE
    Public Const IPxySPDRead As Short = &HCS                            ' PGM-1 Current SPEED DATA READ, 16bit, 0x0000
    Public Const IPxyNoOperation_8C As Short = &H8CS                    ' No operation
    Public Const IPxySPDCMPRead As Short = &HDS                         ' PGM-1 Current SPEED Comparator DATA READ, 16bit, 0x0000
    Public Const IPxySPDCMPWrite As Short = &H8DS                       ' PGM-1 Current SPEED Comparator DATA WRITE
    Public Const IPxyDRVPULSERead As Short = &HES                       ' PGM-1 DRIVE PULSE COUNTER READ, 32bit, 0x00000000
    Public Const IPxyNoOperation_8E As Short = &H8ES                    ' No operation
    Public Const IPxyPRESETPULSERead As Short = &HFS                    ' PGM-1 PRESET PULSE DATA READ, 32bit, 0x00000000
    Public Const IPxyNoOperation_8F As Short = &H8FS                    ' No operation

    ' PGM-1 Update Group Register
    Public Const IPxyURANGERead As Short = &H10S                        ' PGM-1 UP-DATE RANGE READ, 16bit, 0xFFFF
    Public Const IPxyURANGEWrite As Short = &H90S                       ' PGM-1 UP-DATE RANGE WRITE
    Public Const IPxyUSTDRead As Short = &H11S                          ' PGM-1 UP-DATE START/STOP SPEED DATA READ, 16bit, 
    Public Const IPxyUSTDWrite As Short = &H91S                         ' PGM-1 UP-DATE START/STOP SPEED DATA WRITE
    Public Const IPxyUOBJRead As Short = &H12S                          ' PGM-1 UP-DATE OBJECT SPEED DATA READ, 16bit, 
    Public Const IPxyUOBJWrite As Short = &H92S                         ' PGM-1 UP-DATE OBJECT SPEED DATA WRITE
    Public Const IPxyURATE1Read As Short = &H13S                        ' PGM-1 UP-DATE RATE-1 DATA READ, 16bit, 0xFFFF
    Public Const IPxyURATE1Write As Short = &H93S                       ' PGM-1 UP-DATE RATE-1 DATA WRITE
    Public Const IPxyURATE2Read As Short = &H14S                        ' PGM-1 UP-DATE RATE-2 DATA READ, 16bit, 0xFFFF
    Public Const IPxyURATE2Write As Short = &H94S                       ' PGM-1 UP-DATE RATE-2 DATA WRITE
    Public Const IPxyURATE3Read As Short = &H15S                        ' PGM-1 UP-DATE RATE-3 DATA READ, 16bit, 0xFFFF
    Public Const IPxyURATE3Write As Short = &H95S                       ' PGM-1 UP-DATE RATE-3 DATA WRITE
    Public Const IPxyURCP12Read As Short = &H16S                        ' PGM-1 UP-DATE RATE CHANGE POINT 1-2 READ, 16bit, 0xFFFF
    Public Const IPxyURCP12Write As Short = &H96S                       ' PGM-1 UP-DATE RATE CHANGE POINT 1-2 WRITE
    Public Const IPxyURCP23Read As Short = &H17S                        ' PGM-1 UP-DATE RATE CHANGE POINT 2-3 READ, 16bit, 0xFFFF
    Public Const IPxyURCP23Write As Short = &H97S                       ' PGM-1 UP-DATE RATE CHANGE POINT 2-3 WRITE
    Public Const IPxyUSW1Read As Short = &H18S                          ' PGM-1 UP-DATE SW-1 DATA READ, 15bit, 0x7FFF
    Public Const IPxyUSW1Write As Short = &H98S                         ' PGM-1 UP-DATE SW-1 DATA WRITE
    Public Const IPxyUSW2Read As Short = &H19S                          ' PGM-1 UP-DATE SW-2 DATA READ, 15bit, 0x7FFF
    Public Const IPxyUSW2Write As Short = &H99S                         ' PGM-1 UP-DATE SW-2 DATA WRITE
    Public Const IPxyNoOperation_1A As Short = &H1AS                    ' No operation
    Public Const IPxyNoOperation_9A As Short = &H9AS                    ' No operation
    Public Const IPxyUREARRead As Short = &H1BS                         ' PGM-1 UP-DATE SLOW DOWN/REAR PULSE READ, 32bit, 0x00000000
    Public Const IPxyUREARWrite As Short = &H9BS                        ' PGM-1 UP-DATE SLOW DOWN/REAR PULSE WRITE
    Public Const IPxySPDRead_1C As Short = &H1CS                        ' PGM-1 UP-DATA CURRENT SPEED READ(Same with 0x0C)
    Public Const IPxyNoOperation_9C As Short = &H9CS                    ' No operation
    Public Const IPxySPDCMPRead_1D As Short = &H1DS                     ' PGM-1 Current SPEED Comparation DATA READ(Same with 0x0D) 
    Public Const IPxySPDCMPWrite_9D As Short = &H9DS                    ' PGM-1 Current SPEED Compareation DATA WRITE(Same with 0x8D) 
    Public Const IPxyACCPULSERead As Short = &H1ES                      ' PGM-1 Acceleration PULSE COUNTER READ, 32bit, 0x00000000
    Public Const IPxyNoOperation_9E As Short = &H9ES                    ' No operation
    Public Const IPxyPRESETPULSERead_1F As Short = &H1FS                ' PGM-1 PRESET PULSE DATA READ(Same with 0x0F)
    Public Const IPxyNoOperation_9F As Short = &H9FS                    ' No operation

    ' PGM-2 Group Register
    Public Const IPxyNoOperation_20 As Short = &H20S                    ' No operation
    Public Const IPxyPPRESETDRV As Short = &HA0S                        ' +PRESET PULSE DRIVE, 32
    Public Const IPxyNoOperation_21 As Short = &H21S                    ' No operation
    Public Const IPxyPCONTDRV As Short = &HA1s                          ' +CONTINUOUS DRIVE
    Public Const IPxyNoOperation_22 As Short = &H22s                    ' No operation
    Public Const IPxyPSCH1DRV As Short = &HA2s                          ' +SIGNAL SEARCH-1 DRIVE
    Public Const IPxyNoOperation_23 As Short = &H23S                    ' No operation
    Public Const IPxyPSCH2DRV As Short = &HA3S                          ' +SIGNAL SEARCH-2 DRIVE
    Public Const IPxyNoOperation_24 As Short = &H24S                    ' No operation
    Public Const IPxyPORGDRV As Short = &HA4S                           ' +ORIGIN SEARCH DRIVE
    Public Const IPxyNoOperation_25 As Short = &H25S                    ' No operation
    Public Const IPxyMPRESETDRV As Short = &HA5S                        ' -PRESET PULSE DRIVE, 32
    Public Const IPxyNoOperation_26 As Short = &H26S                    ' No operation
    Public Const IPxyMCONTDRV As Short = &HA6S                          ' -CONTINUOUS DRIVE
    Public Const IPxyNoOperation_27 As Short = &H27S                    ' No operation
    Public Const IPxyMSCH1DRV As Short = &HA7S                          ' -SIGNAL SEARCH-1 DRIVE
    Public Const IPxyNoOperation_28 As Short = &H28S                    ' No operation
    Public Const IPxyMSCH2DRV As Short = &HA8S                          ' -SIGNAL SEARCH-2 DRIVE
    Public Const IPxyNoOperation_29 As Short = &H29S                    ' No operation
    Public Const IPxyMORGDRV As Short = &HA9S                           ' -ORIGIN SEARCH DRIVE
    Public Const IPxyPULSEOVERRead As Short = &H2AS                     ' Preset/MPG drive override pulse data read
    Public Const IPxyPULSEOVERWrite As Short = &HAAS                    ' PRESET PULSE DATA OVERRIDE(ON_BUSY)
    Public Const IPxyNoOperation_2B As Short = &H2BS                    ' No operation
    Public Const IPxySSTOPCMD As Short = &HABS                          ' SLOW DOWN STOP
    Public Const IPxyNoOperation_2C As Short = &H2CS                    ' No operation
    Public Const IPxyESTOPCMD As Short = &HACS                          ' EMERGENCY STOP
    Public Const IPxyDRIVEMODERead As Short = &H2DS                     ' Drive mode SETTING DATA READ
    Public Const IPxyDRIVEMODEWrite As Short = &HADS                    ' Drive mode SETTING DATA WRITE
    Public Const IPxyMPGCONRead As Short = &H2ES                        ' MPG OPERATION SETTING DATA READ, 3bit, 0x00
    Public Const IPxyMPGCONWrite As Short = &HAES                       ' MPG OPERATION SETTING DATA WRITE
    Public Const IPxyPULSEMPGRead As Short = &H2FS                      ' MPG PRESET PULSE DATA READ, 32bit, 0x00000000
    Public Const IPxyPULSEMPGWrite As Short = &HAFS                     ' MPG PRESET PULSE DATA WRITE 

    ' Extension Group Register
    Public Const IPxyNoOperation_30 As Short = &H30S                    ' No operation
    Public Const IPxyPSPO1DRV As Short = &HB0S                          ' +SENSOR POSITIONING DRIVE I
    Public Const IPxyNoOperation_31 As Short = &H31S                    ' No operation
    Public Const IPxyMSPO1DRV As Short = &HB1S                          ' -SENSOR POSITIONING DRIVE I
    Public Const IPxyNoOperation_32 As Short = &H32S                    ' No operation
    Public Const IPxyPSPO2DRV As Short = &HB2S                          ' +SENSOR POSITIONING DRIVE II
    Public Const IPxyNoOperation_33 As Short = &H33S                    ' No operation
    Public Const IPxyMSPO2DRV As Short = &HB3S                          ' -SENSOR POSITIONING DRIVE II
    Public Const IPxyNoOperation_34 As Short = &H34S                    ' No operation
    Public Const IPxyPSPO3DRV As Short = &HB4S                          ' +SENSOR POSITIONING DRIVE III
    Public Const IPxyNoOperation_35 As Short = &H35S                    ' No operation
    Public Const IPxyMSPO3DRV As Short = &HB5S                          ' -SENSOR POSITIONING DRIVE III
    Public Const IPxySWLMTCONRead As Short = &H36S                      ' SOFT LIMIT SETTING READ, 3bit, 0x00
    Public Const IPxySWLMTCONWrite As Short = &HB6S                     ' SOFT LIMIT SETTING WRITE
    Public Const IPxyMSWLMTCOMPRead As Short = &H37S                    ' -SOFT LIMIT Comparation DATA SETTING READ, 32bit, 0x80000000
    Public Const IPxyMSWLMTCOMPWrite As Short = &HB7S                   ' -SOFT LIMIT Comparation DATA SETTING WRITE
    Public Const IPxyPSWLMTCOMPRead As Short = &H38S                    ' +SOFT LIMIT Comparation DATA SETTING READ, 32bit, 0x7FFFFFFF
    Public Const IPxyPSWLMTCOMPWrite As Short = &HB8S                   ' +SOFT LIMIT Comparation DATA SETTING WRITE
    Public Const IPxyTRGCONRead As Short = &H39S                        ' TRIGGER MODE SETTING READ, 32bit, 0x00010000
    Public Const IPxyTRGCONWrite As Short = &HB9S                       ' TRIGGER MODE SETTING WRITE
    Public Const IPxyTRGCOMPRead As Short = &H3AS                       ' TRIGGER Comparation DATA SETTING READ, 32bit, 0x00000000
    Public Const IPxyTRGCOMPWrite As Short = &HBAS                      ' TRIGGER Comparation DATA SETTING WRITE
    Public Const IPxyICMRead As Short = &H3BS                           ' INTERNAL M-DATA SETTING READ, 32bit, 0x80000000
    Public Const IPxyICMWrite As Short = &HBBS                          ' INTERNAL M-DATA SETTING WRITE
    Public Const IPxyECMRead As Short = &H3CS                           ' EXTERNAL M-DATA SETTING READ, 32bit, 0x80000000
    Public Const IPxyECMWrite As Short = &HBCS                          ' EXTERNAL M-DATA SETTING WRITE
    Public Const IPxySTOPPWRead As Short = &H3DS                        ' Stop pulse width Read
    Public Const IPxySTOPPWWrite As Short = &HBDS                       ' Stop pulse width Write
    Public Const IPxyNoOperation_3E As Short = &H3ES                    ' No operation
    Public Const IPxyNoOperation_BE As Short = &HBES                    ' No operation
    Public Const IPxyNoOperation_3F As Short = &H3FS                    ' No operation
    Public Const IPxyTRGCMD As Short = &HBFS                            ' TRIG output signal generation command

    ' Interpolation Group Registers
    Public Const IPxCIRXCRead As Short = &H40S                          ' Circular interpolation X axis center point read
    Public Const IPxCIRXCWrite As Short = &HC0S                         ' Circular interpolation X axis center point write 
    Public Const IPxCIRYCRead As Short = &H41S                          ' Circular interpolation Y axis center point read 
    Public Const IPxCIRYCWrite As Short = &HC1S                         ' Circular interpolation Y axis center point write  
    Public Const IPxENDXRead As Short = &H42S                           ' Interpolation X axis end point read 
    Public Const IPxENDXWrite As Short = &HC2S                          ' Interpolation X axis end point write  
    Public Const IPxENDYRead As Short = &H43S                           ' Interpolation Y axis end point read  
    Public Const IPxENDYWrite As Short = &HC3S                          ' Interpolation Y axis end point write  
    Public Const IPxPTXENDRead As Short = &H44S                         ' Pattern interpolation X Queue data read
    Public Const IPxPTXENDWrite As Short = &HC4S                        ' Pattern interpolation X Queue data with queue push 
    Public Const IPxPTYENDRead As Short = &H45S                         ' Pattern interpolation Y Queue data read 
    Public Const IPxPTYENDWrite As Short = &HC5S                        ' Pattern interpolation Y Queue data write
    Public Const IPxPTQUEUERead As Short = &H46S                        ' Pattern interpolation Queue index read
    Public Const IPxNoOperation_C6 As Short = &HC6S                     ' No operation
    Public Const IPxNoOperation_47 As Short = &H47S                     ' No operation
    Public Const IPxNoOperation_C7 As Short = &HC7S                     ' No operation
    Public Const IPxNoOperation_48 As Short = &H48S                     ' No operation
    Public Const IPxNoOperation_C8 As Short = &HC8S                     ' No operation
    Public Const IPxNoOperation_49 As Short = &H49S                     ' No operation
    Public Const IPxNoOperation_C9 As Short = &HC9S                     ' No operation
    Public Const IPxINPSTATUSRead As Short = &H4AS                      ' Interpolation Status register read
    Public Const IPxNoOperation_CA As Short = &HCAS                     ' No operation
    Public Const IPxINPMODE_4B As Short = &H4BS                         ' Interpolation mode in Queue TOP contets
    Public Const IPxLINPDRV As Short = &HCBS                            ' Linear interpolation with Queue push
    Public Const IPxINPMODE_4C As Short = &H4CS                         ' Interpolation mode in Queue TOP contets
    Public Const IPxCINPDRV As Short = &HCCS                            ' Circular interpolation with Queue push 
    Public Const IPxBPINPMODE As Short = &H4DS                          ' Bit Pattern Interpolation mode in Queue TOP contets
    Public Const IPxBPINPDRV As Short = &HCDS                           ' Bit pattern Drive
    Public Const IPxNoOperation_4E As Short = &H4ES                     ' No Operation
    Public Const IPxNoOperation_CE As Short = &HCES                     ' No Operation 
    Public Const IPxNoOperation_4F As Short = &H4FS                     ' No Operation 
    Public Const IPxNoOperation_CF As Short = &HCFS                     ' No Operation 

    ' Arithemetic Group Register
    Public Const IPxNoOperation_50 As Short = &H50S                     ' No Operation
    Public Const IPxINPCLR As Short = &HD0S                             ' Initialize all interpolation control block
    Public Const IPxINPMPOINTRead As Short = &H51S                      ' Interpolation deceleration manual point(unsigned) read
    Public Const IPxINPMPOINTWrite As Short = &HD1S                     ' Interpolation deceleration manual point(unsigned) write
    Public Const IPxNoOperation_52 As Short = &H52S                     ' No Operation
    Public Const IPxINPCLRSWrite As Short = &HD2S                       ' Initialize interpolation control block with target selection
    Public Const IPxNoOperation_53 As Short = &H53S                     ' No Operation
    Public Const IPxINPDRVWrite As Short = &HD3S                        ' linear/circular drive start with queue data(Hold on mode), Restart on pause
    Public Const IPxNoOperation_54 As Short = &H54S                     ' No operation
    Public Const IPxNoOperation_D4 As Short = &HD4S                     ' No operation
    Public Const IPxNoOperation_55 As Short = &H55S                     ' No operation
    Public Const IPxARTSHOT As Short = &HD5S                            ' Arithmetic block One time execution
    Public Const IPxARTSHOPERRead As Short = &H56S                      ' Arithmetic block shift and operation selection Read
    Public Const IPxARTSHOPERWrite As Short = &HD6S                     ' Arithmetic block shift and operation selection Write
    Public Const IPxARTSHRead As Short = &H57S                          ' Arithmetic block shift amount data Read
    Public Const IPxARTSHWrite As Short = &HD7S                         ' Arithmetic block shift amount data Write
    Public Const IPxARTSOURCERead As Short = &H58S                      ' Arithmetic block operand configure data Read
    Public Const IPxARTSOURCEWrite As Short = &HD8S                     ' Arithmetic block operand configure data Write
    Public Const IPxARTCRESULT1Read As Short = &H59S                    ' Arithmetic first compare result data Read
    Public Const IPxNoOperation_D9 As Short = &HD9S                     ' No Operation
    Public Const IPxARTCRESULT2Read As Short = &H5AS                    ' Arithmetic second compare result data Read
    Public Const IPxNoOperation_DA As Short = &HDAS                     ' No Operation
    Public Const IPxARTARESULT1Read As Short = &H5BS                    ' Arithmetic first algebraic result data Read
    Public Const IPxNoOperation_DB As Short = &HDBS                     ' No Operation
    Public Const IPxARTARESULT2Read As Short = &H5CS                    ' Arithmetic second algebraic result data Read
    Public Const IPxNoOperation_DC As Short = &HDCS                     ' No operation
    Public Const IPxARTUSERARead As Short = &H5DS                       ' Arithmetic block User operand A Read
    Public Const IPxARTUSERAWrite As Short = &HDDS                      ' Arithmetic block User operand A Write
    Public Const IPxARTUSERBRead As Short = &H5ES                       ' Arithmetic block User operand B Read
    Public Const IPxARTUSERBWrite As Short = &HDES                      ' Arithmetic block User operand B Write
    Public Const IPxARTUSERCRead As Short = &H5FS                       ' Arithmetic block User operand C Read
    Public Const IPxARTUSERCWrite As Short = &HDFS                      ' Arithmetic block User operand C Write

    ' Scripter Group Register
    Public Const IPySCRCON1Read As Short = &H40S                        ' Script Control SETTING DATA-1 READ, 32bit, 0x00000000
    Public Const IPySCRCON1Write As Short = &HC0S                       ' Script Control SETTING DATA-1 WRITE
    Public Const IPySCRCON2Read As Short = &H41S                        ' Script Control SETTING DATA-2 READ, 32bit, 0x00000000
    Public Const IPySCRCON2Write As Short = &HC1S                       ' Script Control SETTING DATA-2 WRITE
    Public Const IPySCRCON3Read As Short = &H42S                        ' Script Control SETTING DATA-3 READ, 32bit, 0x00000000 
    Public Const IPySCRCON3Write As Short = &HC2S                       ' Script Control SETTING DATA-3 WRITE
    Public Const IPySCRCONQRead As Short = &H43S                        ' Script Control SETTING DATA-Queue READ, 32bit, 0x00000000
    Public Const IPySCRCONQWrite As Short = &HC3S                       ' Script Control SETTING DATA-Queue WRITE
    Public Const IPySCRDATA1Read As Short = &H44S                       ' Script Control DATA DATA-1 READ, 32bit, 0x00000000 
    Public Const IPySCRDATA1Write As Short = &HC4S                      ' Script Control DATA DATA-1 WRITE
    Public Const IPySCRDATA2Read As Short = &H45S                       ' Script Control DATA DATA-2 READ, 32bit, 0x00000000 
    Public Const IPySCRDATA2Write As Short = &HC5S                      ' Script Control DATA DATA-2 WRITE
    Public Const IPySCRDATA3Read As Short = &H46S                       ' Script Control DATA DATA-3 READ, 32bit, 0x00000000 
    Public Const IPySCRDATA3Write As Short = &HC6S                      ' Script Control DATA DATA-3 WRITE
    Public Const IPySCRDATAQRead As Short = &H47S                       ' Script Control DATA DATA-Queue READ, 32bit, 0x00000000 
    Public Const IPySCRDATAQWrite As Short = &HC7S                      ' Script Control DATA DATA-Queue WRITE
    Public Const IPyNoOperation_48 As Short = &H48S                     ' No operation
    Public Const IPySCRQCLR As Short = &HC8S                            ' Script Queue clear
    Public Const IPySCRCQSIZERead As Short = &H49S                      ' Script Control SETTING Queue index READ, 4bit, 0x00
    Public Const IPyNoOperation_C9 As Short = &HC9S                     ' No operation
    Public Const IPySCRDQSIZERead As Short = &H4AS                      ' Script Control DATA Queue index READ, 4bit, 0x00
    Public Const IPyNoOperation_CA As Short = &HCAS                     ' No operation
    Public Const IPySCRQFLAGRead As Short = &H4BS                       ' Script Queue Full/Empty Flag READ, 4bit, 0x05
    Public Const IPyNoOperation_CB As Short = &HCBS                     ' No operation
    Public Const IPySCRQSIZECONRead As Short = &H4CS                    ' Script Queue size SETTING(0~13) READ, 16bit, 0xD0D0
    Public Const IPySCRQSIZECONWrite As Short = &HCCS                   ' Script Queue size SETTING(0~13) WRITE
    Public Const IPySCRQSTATUSRead As Short = &H4DS                     ' Script Queue status READ, 12bit, 0x005
    Public Const IPyNoOperation_CD As Short = &HCDS                     ' No operation
    Public Const IPyNoOperation_4E As Short = &H4ES                     ' No operation
    Public Const IPyNoOperation_CE As Short = &HCES                     ' No operation
    Public Const IPyNoOperation_4F As Short = &H4FS                     ' No operation
    Public Const IPyNoOperation_CF As Short = &HCFS                     ' No operation

    ' Caption Group Register
    Public Const IPyCAPCON1Read As Short = &H50S                        ' Caption Control SETTING DATA-1 READ, 32bit, 0x00000000
    Public Const IPyCAPCON1Write As Short = &HD0S                       ' Caption Control SETTING DATA-1 WRITE
    Public Const IPyCAPCON2Read As Short = &H51S                        ' Caption Control SETTING DATA-2 READ, 32bit, 0x00000000
    Public Const IPyCAPCON2Write As Short = &HD1S                       ' Caption Control SETTING DATA-2 WRITE
    Public Const IPyCAPCON3Read As Short = &H52S                        ' Caption Control SETTING DATA-3 READ, 32bit, 0x00000000 
    Public Const IPyCAPCON3Write As Short = &HD2S                       ' Caption Control SETTING DATA-3 WRITE
    Public Const IPyCAPCONQRead As Short = &H53S                        ' Caption Control SETTING DATA-Queue READ, 32bit, 0x00000000
    Public Const IPyCAPCONQWrite As Short = &HD3S                       ' Caption Control SETTING DATA-Queue WRITE
    Public Const IPyCAPDATA1Read As Short = &H54S                       ' Caption Control DATA DATA-1 READ, 32bit, 0x00000000 
    Public Const IPyNoOperation_D4 As Short = &HD4S                     ' No operation
    Public Const IPyCAPDATA2Read As Short = &H55S                       ' Caption Control DATA DATA-2 READ, 32bit, 0x00000000 
    Public Const IPyNoOperation_D5 As Short = &HD5S                     ' No operation
    Public Const IPyCAPDATA3Read As Short = &H56S                       ' Caption Control DATA DATA-3 READ, 32bit, 0x00000000 
    Public Const IPyNoOperation_D6 As Short = &HD6S                     ' No operation
    Public Const IPyCAPDATAQRead As Short = &H57S                       ' Caption Control DATA DATA-Queue READ, 32bit, 0x00000000 
    Public Const IPyNoOperation_D7 As Short = &HD7S                     ' No operation
    Public Const IPyNoOperation_58 As Short = &H58S                     ' No operation
    Public Const IPyCAPQCLR As Short = &HD8S                            ' Caption Queue clear
    Public Const IPyCAPCQSIZERead As Short = &H59S                      ' Caption Control SETTING Queue index READ, 4bit, 0x00
    Public Const IPyNoOperation_D9 As Short = &HD9S                     ' No operation
    Public Const IPyCAPDQSIZERead As Short = &H5AS                      ' Caption Control DATA Queue index READ, 4bit, 0x00
    Public Const IPyNoOperation_DA As Short = &HDAS                     ' No operation
    Public Const IPyCAPQFLAGRead As Short = &H5BS                       ' Caption Queue Full/Empty Flag READ, 4bit, 0x05
    Public Const IPyNoOperation_DB As Short = &HDBS                     ' No operation
    Public Const IPyCAPQSIZECONRead As Short = &H5CS                    ' Caption Queue size SETTING(0~13) READ, 16bit, 0xD0D0
    Public Const IPyCAPQSIZECONWrite As Short = &HDCS                   ' Caption Queue size SETTING(0~13) WRITE
    Public Const IPyCAPQSTATUSRead As Short = &H5DS                     ' Caption Queue status READ, 12bit, 0x005
    Public Const IPyNoOperation_DD As Short = &HDDS                     ' No operation
    Public Const IPyNoOperation_5E As Short = &H5ES                     ' No operation
    Public Const IPyNoOperation_DE As Short = &HDES                     ' No operation
    Public Const IPyNoOperation_5F As Short = &H5FS                     ' No operation
    Public Const IPyNoOperation_DF As Short = &HDFS                     ' No operation

    ' BUS - 1 Group Register
    Public Const IPxyINCNTRead As Short = &H60S                         ' INTERNAL COUNTER DATA READ(Signed), 32bit, 0x00000000
    Public Const IPxyINCNTWrite As Short = &HE0S                        ' INTERNAL COUNTER DATA WRITE(Signed)
    Public Const IPxyINCNTCMPRead As Short = &H61S                      ' INTERNAL COUNTER COMPARATE DATA READ(Signed), 32bit, 0x00000000
    Public Const IPxyINCNTCMPWrite As Short = &HE1S                     ' INTERNAL COUNTER COMPARATE DATA WRITE(Signed)
    Public Const IPxyINCNTSCALERead As Short = &H62S                    ' INTERNAL COUNTER PRE-SCALE DATA READ, 8bit, 0x00
    Public Const IPxyINCNTSCALEWrite As Short = &HE2S                   ' INTERNAL COUNTER PRE-SCALE DATA WRITE
    Public Const IPxyICPRead As Short = &H63S                           ' INTERNAL COUNTER P-DATA READ, 32bit, 0x7FFFFFFF
    Public Const IPxyICPWrite As Short = &HE3S                          ' INTERNAL COUNTER P-DATA WRITE
    Public Const IPxyEXCNTRead As Short = &H64S                         ' EXTERNAL COUNTER DATA READ READ(Signed), 32bit, 0x00000000
    Public Const IPxyEXCNTWrite As Short = &HE4S                        ' EXTERNAL COUNTER DATA READ WRITE(Signed)
    Public Const IPxyEXCNTCMPRead As Short = &H65S                      ' EXTERNAL COUNTER COMPARATE DATA READ(Signed), 32bit, 0x00000000
    Public Const IPxyEXCNTCMPWrite As Short = &HE5S                     ' EXTERNAL COUNTER COMPARATE DATA WRITE(Signed)
    Public Const IPxyEXCNTSCALERead As Short = &H66S                    ' EXTERNAL COUNTER PRE-SCALE DATA READ, 8bit, 0x00
    Public Const IPxyEXCNTSCALEWrite As Short = &HE6S                   ' EXTERNAL COUNTER PRE-SCALE DATA WRITE
    Public Const IPxyEXPRead As Short = &H67S                           ' EXTERNAL COUNTER P-DATA READ, 32bit, 0x7FFFFFFF
    Public Const IPxyEXPWrite As Short = &HE7S                          ' EXTERNAL COUNTER P-DATA WRITE
    Public Const IPxyEXSPDRead As Short = &H68S                         ' EXTERNAL SPEED DATA READ, 32bit, 0x00000000
    Public Const IPxyNoOperation_E8 As Short = &HE8S                    ' No operation
    Public Const IPxyEXSPDCMPRead As Short = &H69S                      ' EXTERNAL SPEED COMPARATE DATA READ, 32bit, 0x00000000
    Public Const IPxyEXSPDCMPWrite As Short = &HE9S                     ' EXTERNAL SPEED COMPARATE DATA WRITE
    Public Const IPxyEXFILTERDRead As Short = &H6AS                     ' External sensor bandwidth SETTING DATA READ, 32bit, 0x00050005
    Public Const IPxyEXFILTERDWrite As Short = &HEAS                    ' External sensor bandwidth SETTING DATA WRITE
    Public Const IPxyOFFREGIONRead As Short = &H6BS                     ' OFF-RANGE DATA READ, 8bit, 0x00
    Public Const IPxyOFFREGIONWrite As Short = &HEBS                    ' OFF-RANGE DATA WRITE
    Public Const IPxyDEVIATIONRead As Short = &H6CS                     ' DEVIATION DATA READ, 16bit, 0x0000
    Public Const IPxyNoOperation_EC As Short = &HECS                    ' No operation
    Public Const IPxyPGMCHRead As Short = &H6DS                         ' PGM REGISTER CHANGE DATA READ
    Public Const IPxyPGMCHWrite As Short = &HEDS                        ' PGM REGISTER CHANGE DATA WRITE
    Public Const IPxyCOMPCONRead As Short = &H6ES                       ' COMPARE REGISTER INPUT CHANGE DATA READ
    Public Const IPxyCOMPCONWrite As Short = &HEES                      ' COMPARE REGISTER INPUT CHANGE DATA WRITE
    Public Const IPxyNoOperation_6F As Short = &H6FS                    ' No operation
    Public Const IPxyNoOperation_EF As Short = &HEFS                    ' No operation

    ' BUS - 2 Group Register
    Public Const IPxyFUNCONRead As Short = &H70S                        ' Function SETTING DATA READ,
    Public Const IPxyFUNCONWrite As Short = &HF0S                       ' Function SETTING DATA WRITE
    Public Const IPxyMODE1Read As Short = &H71S                         ' MODE1 DATA READ,
    Public Const IPxyMODE1Write As Short = &HF1S                        ' MODE1 DATA WRITE
    Public Const IPxyMODE2Read As Short = &H72S                         ' MODE2 DATA READ,
    Public Const IPxyMODE2Write As Short = &HF2S                        ' MODE2 DATA WRITE
    Public Const IPxyUIODATARead As Short = &H73S                       ' UNIVERSAL IN READ,
    Public Const IPxyUIODATAWrite As Short = &HF3S                      ' UNIVERSAL OUT WRITE
    Public Const IPxyENDSTATUSRead As Short = &H74S                     ' END STATUS DATA READ,
    Public Const IPxyCLIMCLR As Short = &HF4S                           ' Complete limit stop clear command
    Public Const IPxyMECHRead As Short = &H75S                          ' MECHANICAL SIGNAL DATA READ, 13bit
    Public Const IPxyNoOperation_F5 As Short = &HF5S                    ' No operation
    Public Const IPxyDRVSTATUSRead As Short = &H76S                     ' DRIVE STATE DATA READ, 20bit
    Public Const IPxyNoOperation_F6 As Short = &HF6S                    ' No operation
    Public Const IPxyEXCNTCLRRead As Short = &H77S                      ' EXTERNAL COUNTER SETTING DATA READ, 9bit, 0x00
    Public Const IPxyEXCNTCLRWrite As Short = &HF7S                     ' EXTERNAL COUNTER SETTING DATA WRITE
    Public Const IPxyNoOperation_78 As Short = &H78S                    ' No operation
    Public Const IPxySWRESET As Short = &HF8S                           ' REGISTER CLEAR(INITIALIZATION), Software reset
    Public Const IPxyINTFLAG1Read As Short = &H79S                      ' Interrupt Flag1 READ, 32bit, 0x00000000
    Public Const IPxyINTFLAG1CLRWrite As Short = &HF9S                  ' Interrupt Flag1 Clear data write command.
    Public Const IPxyINTMASK1Read As Short = &H7AS                      ' Interrupt Mask1 READ, 32bit, 0x00000001
    Public Const IPxyINTMASK1Write As Short = &HFAS                     ' Interrupt Mask1 WRITE
    Public Const IPxyUIOMODERead As Short = &H7BS                       ' UIO MODE DATA READ, 12bit, 0x01F
    Public Const IPxyUIOMODEWrite As Short = &HFBS                      ' UIO MODE DATA WRITE
    Public Const IPxyINTFLAG2Read As Short = &H7CS                      ' Interrupt Flag2 READ, 32bit, 0x00000000
    Public Const IPxyINTFLAG2CLRWrite As Short = &HFCS                  ' Interrupt Flag2 Clear data write command.
    Public Const IPxyINTMASK2Read As Short = &H7DS                      ' Interrupt Mask2 READ, 32bit, 0x00000001
    Public Const IPxyINTMASK2Write As Short = &HFDS                     ' Interrupt Mask2 WRITE
    Public Const IPxyINTUSERCONRead As Short = &H7ES                    ' User interrupt selection control.
    Public Const IPxyINTUSERCONWrite As Short = &HFES                   ' User interrupt selection control. 
    Public Const IPxyNoOperation_7F As Short = &H7FS                    ' No operation
    Public Const IPxyINTGENCMD As Short = &HFFS                         ' Interrupt generation command.

    ' { QI COMMAND LIST }
    ' Previous register and etc Registers
    Public Const QiPRANGERead As Short = &H0                            ' Previous RANGE READ
    Public Const QiPRANGEWrite As Short = &H80                          ' Previous RANGE WRITE
    Public Const QiPSTDRead As Short = &H1                              ' Previous START/STOP SPEED DATA READ
    Public Const QiPSTDWrite As Short = &H81                            ' Previous START/STOP SPEED DATA WRITE
    Public Const QiPOBJRead As Short = &H2                              ' Previous OBJECT SPEED DATA READ
    Public Const QiPOBJWrite As Short = &H82                            ' Previous OBJECT SPEED DATA WRITE
    Public Const QiPRATE1Read As Short = &H3                            ' Previous RATE-1 DATA READ
    Public Const QiPRATE1Write As Short = &H83                          ' Previous RATE-1 DATA WRITE
    Public Const QiPRATE2Read As Short = &H4                            ' Previous RATE-2 DATA READ
    Public Const QiPRATE2Write As Short = &H84                          ' Previous RATE-2 DATA WRITE
    Public Const QiPSW1Read As Short = &H5                              ' Previous SW-1 DATA READ
    Public Const QiPSW1Write As Short = &H85                            ' Previous SW-1 DATA WRITE
    Public Const QiPSW2Read As Short = &H6                              ' Previous SW-2 DATA READ
    Public Const QiPSW2Write As Short = &H86                            ' Previous SW-2 DATA WRITE
    Public Const QiPDCFGRead As Short = &H7                             ' Previous Drive configure data READ
    Public Const QiPDCFGWrite As Short = &H87                           ' Previous Drive configure data WRITE
    Public Const QiPREARRead As Short = &H8                             ' Previous SLOW DOWN/REAR PULSE READ
    Public Const QiPREARWrite As Short = &H88                           ' Previous SLOW DOWN/REAR PULSE WRITE
    Public Const QiPPOSRead As Short = &H9                              ' Previous Drive pulse amount data/Interpolation end position READ
    Public Const QiPPOSWrite As Short = &H89                            ' Previous Drive pulse amount data/Interpolation end position WRITE
    Public Const QiPCENTRead As Short = &HA                             ' Previous Circular Int. center/Master axis target position for multiple chip linear int. READ
    Public Const QiPCENTWrite As Short = &H8A                           ' Previous Circular Int. center/Master axis target position for multiple chip linear int. WRITE
    Public Const QiPISNUMRead As Short = &HB                            ' Previous Interpolation step number READ
    Public Const QiPISNUMWrite As Short = &H8B                          ' Previous Interpolation step number WRITE
    Public Const QiNoOperation_0C As Short = &HC                        ' No operation
    Public Const QiCLRPRE As Short = &H8C                               ' Clear previous driving data Queue.
    Public Const QiNoOperation_0D As Short = &HD                        ' No operation
    Public Const QiPOPPRE As Short = &H8D                               ' Pop and shift data of previous driving data Queue.
    Public Const QiPPORTMARestore As Short = &HE                        ' Restore data ports.
    Public Const QiPPORTMABackup As Short = &H8E                        ' Backup data ports.
    Public Const QiCURSPDRead As Short = &HF                            ' Current SPEED DATA READ
    Public Const QiNoOperation_8F As Short = &H8F                       ' No operation
    ' Working Registers
    Public Const QiRANGERead As Short = &H10                            ' RANGE READ
    Public Const QiRANGEWrite As Short = &H90                           ' RANGE WRITE
    Public Const QiSTDRead As Short = &H11                              ' START/STOP SPEED DATA READ
    Public Const QiSTDWrite As Short = &H91                             ' START/STOP SPEED DATA WRITE
    Public Const QiOBJRead As Short = &H12                              ' OBJECT SPEED DATA READ
    Public Const QiOBJWrite As Short = &H92                             ' OBJECT SPEED DATA WRITE
    Public Const QiRATE1Read As Short = &H13                            ' RATE-1 DATA READ
    Public Const QiRATE1Write As Short = &H93                           ' RATE-1 DATA WRITE
    Public Const QiRATE2Read As Short = &H14                            ' RATE-2 DATA READ
    Public Const QiRATE2Write As Short = &H94                           ' RATE-2 DATA WRITE
    Public Const QiSW1Read As Short = &H15                              ' SW-1 DATA READ
    Public Const QiSW1Write As Short = &H95                             ' SW-1 DATA WRITE
    Public Const QiSW2Read As Short = &H16                              ' SW-2 DATA READ
    Public Const QiSW2Write As Short = &H96                             ' SW-2 DATA WRITE
    Public Const QiDCFGRead As Short = &H17                             ' Drive configure data READ
    Public Const QiDCFGWrite As Short = &H97                            ' Drive configure data WRITE
    Public Const QiREARRead As Short = &H18                             ' SLOW DOWN/REAR PULSE READ
    Public Const QiREARWrite As Short = &H98                            ' SLOW DOWN/REAR PULSE WRITE
    Public Const QiPOSRead As Short = &H19                              ' Drive pulse amount data/Interpolation end position READ
    Public Const QiPOSWrite As Short = &H99                             ' Drive pulse amount data/Interpolation end position WRITE
    Public Const QiCENTRead As Short = &H1A                             ' Circular Int. center/Master axis target position for multiple chip linear int. READ
    Public Const QiCENTWrite As Short = &H9A                            ' Circular Int. center/Master axis target position for multiple chip linear int. WRITE
    Public Const QiISNUMRead As Short = &H1B                            ' Interpolation step number READ
    Public Const QiISNUMWrite As Short = &H9B                           ' Interpolation step number WRITE
    Public Const QiREMAIN As Short = &H1C                               ' Remain pulse data after stopping preset drive function abnormally.
    Public Const QiNoOperation_9C As Short = &H9C                       ' No operation
    Public Const QiOBJORGRead As Short = &H1F                           ' Original search object speed READ
    Public Const QiOBJORGWrite As Short = &H9F                          ' Original search object speed WRITE
    ' Universal in/out setting
    Public Const QiUIOMRead As Short = &H1D                             ' Universal in/out terminal mode READ
    Public Const QiUIOMWrite As Short = &H9D                            ' Universal in/out terminal mode WRITE
    Public Const QiUIORead As Short = &H1E                              ' Universal in/out terminal mode READ
    Public Const QiUIOWrite As Short = &H9E                             ' Universal in/out terminal mode WRIT
    ' Drive start command
    Public Const QiNoOperation_20 As Short = &H20                       ' No operation.
    Public Const QiSTRN As Short = &HA0                                 ' Normal profile mode drive start.(STD As Short => OBJ As Short => STD)
    Public Const QiNoOperation_21 As Short = &H21                       ' No operation.
    Public Const QiSTRO As Short = &HA0                                 ' Start at OBJ profile mode drive start.(OBJ As Short => STD)
    Public Const QiNoOperation_22 As Short = &H22                       ' No operation.
    Public Const QiSTRCO As Short = &HA0                                ' Constant speed profile #1 drive start.(OBJ)
    Public Const QiNoOperation_23 As Short = &H23                       ' No operation.
    Public Const QiSTRCS As Short = &HA0                                ' Constant speed profile #2 drive start.(STD)
    Public Const QiNoOperation_60 As Short = &H5C                       ' No operation.
    Public Const QiASTRN As Short = &HDC                                ' Normal profile mode drive start with DCFG7~0 bit data in DATAPL0 port.(STD As Short => OBJ As Short => STD)
    Public Const QiNoOperation_61 As Short = &H5D                       ' No operation.
    Public Const QiASTRO As Short = &HDD                                ' Start at OBJ profile mode drive start with DCFG7~0 bit data in DATAPL0 port.(OBJ As Short => STD)
    Public Const QiNoOperation_62 As Short = &H5E                       ' No operation.
    Public Const QiASTRCO As Short = &HDE                               ' Constant speed profile #1 drive start with DCFG7~0 bit data in DATAPL0 port.(OBJ)
    Public Const QiNoOperation_63 As Short = &H5F                       ' No operation.
    Public Const QiASTRCS As Short = &HDF                               ' Constant speed profile #2 drive start with DCFG7~0 bit data in DATAPL0 port.(STD)
    ' Drive control command
    Public Const QiNoOperation_24 As Short = &H24                       ' No operation.
    Public Const QiSSTOP As Short = &HA4                                ' Slow Down stop.
    Public Const QiNoOperation_25 As Short = &H25                       ' No operation.
    Public Const QiSTOP As Short = &HA5                                 ' Immediately stop.
    Public Const QiNoOperation_26 As Short = &H26                       ' No operation.
    Public Const QiSQRO1 As Short = &HA6                                ' Output one shot of the start pulse form SQSTR1 terminal.
    Public Const QiNoOperation_27 As Short = &H27                       ' No operation.
    Public Const QiSQRO2 As Short = &HA7                                ' Output one shot of the start pulse form SQSTR2 terminal.
    Public Const QiNoOperation_28 As Short = &H28                       ' No operation.
    Public Const QiSQRI1 As Short = &HA8                                ' Execution sync start function same as SQSTR1 input.
    Public Const QiNoOperation_29 As Short = &H29                       ' No operation.
    Public Const QiSQRI2 As Short = &HA9                                ' Execution sync start function same as SQSTR2 input.
    Public Const QiNoOperation_2A As Short = &H2A                       ' No operation
    Public Const QiSQSTP1 As Short = &HAA                               ' Output one shot of the stop pulse from SQSTP1 terminal.
    Public Const QiNoOperation_2B As Short = &H2B                       ' No operation.
    Public Const QiSQSTP2 As Short = &HAB                               ' Output one shot of the stop pulse from SQSTP2 terminal.
    Public Const QiISCNTRead As Short = &H2C                            ' Interpolation stop counter value READ.
    Public Const QiNoOperation_AC As Short = &HAC                       ' No operation.
    Public Const QiISACNTRead As Short = &H2D                           ' Interpolation step counter READ for advanced deceleration mode .
    Public Const QiNoOperation_AD As Short = &HAD                       ' No operation.
    Public Const QiNoOperation_2E As Short = &H2E                       ' No operation.
    Public Const QiESTOP As Short = &HAE                                ' Emergency stop all axis.
    Public Const QiNoOperation_2F As Short = &H2F                       ' No operation
    Public Const QiSWRESET As Short = &HAF                              ' Software reset(all axis).
    Public Const QiNoOperation_30 As Short = &H30                       ' Driven pulse amount during last driving(Interpolation step counter for path move).
    Public Const QiDRPCNTRead As Short = &H30                           ' No operation
    Public Const QiNoOperation_B0 As Short = &HB0                       ' Driven pulse amount during last driving(Interpolation step counter for path move).
    Public Const QiNoOperation_31 As Short = &H31                       ' No operation
    Public Const QiINTGEN As Short = &HB1                               ' Interrupt generation command.
    ' Peripheral function setting
    Public Const QiNoOperation_33 As Short = &H32                       ' No operation.
    Public Const QiTRGQPOP As Short = &HB2                              ' Pop and shift data in trigger position queue.
    Public Const QiTRTMCFRead As Short = &H33                           ' Trigger/Timer configure READ.
    Public Const QiTRTMCFWrite As Short = &HB3                          ' Trigger/Timer configure WRITE.
    Public Const QiSNSMTRead As Short = &H34                            ' Software negative limit position READ.
    Public Const QiSNSMTWrite As Short = &HB4                           ' Software negative limit position WRITE.
    Public Const QiSPSMTRead As Short = &H35                            ' Software positive limit position READ.
    Public Const QiSPSMTWrite As Short = &HB5                           ' Software positive limit position WRITE.
    Public Const QiTRGPWRead As Short = &H36                            ' Trigger pulse width READ.
    Public Const QiTRGPWWrite As Short = &HB6                           ' Trigger pulse width WRITE.
    Public Const QiTRGSPRead As Short = &H37                            ' Trigger function start position READ.
    Public Const QiTRGSPWrite As Short = &HB7                           ' Trigger function start position WRITE.
    Public Const QiTRGEPRead As Short = &H38                            ' Trigger function end position READ.
    Public Const QiTRGEPWrite As Short = &HB8                           ' Trigger function end position WRITE.
    Public Const QiPTRGPOSRead As Short = &H39                          ' Trigger position or period queue data READ.
    Public Const QiPTRGPOSWrite As Short = &HB9                         ' Push trigger position or period queue.
    Public Const QiNoOperation_3A As Short = &H3A                       ' No operation.
    Public Const QiCLRTRIG As Short = &HBA                              ' Clear trigger position or period queue.
    Public Const QiNoOperation_3B As Short = &H3B                       ' No operation.
    Public Const QiTRGGEN As Short = &HBB                               ' Generate one shot trigger pulse.
    Public Const QiTMRP1Read As Short = &H3C                            ' Timer #1 period data READ.
    Public Const QiTMRP1Write As Short = &HBC                           ' Timer #1 period data WRITE.
    Public Const QiTMRP2Read As Short = &H3D                            ' Timer #2 period data READ.
    Public Const QiTMRP2Write As Short = &HBD                           ' Timer #2 period data WRITE.
    Public Const QiTMR1GENstop As Short = &H3E                          ' Timer #1 stop.
    Public Const QiTMR1GENstart As Short = &HBE                         ' Timer #1 start.
    Public Const QiTMR2GENstop As Short = &H3F                          ' Timer #2 stop.
    Public Const QiTMR2GENstart As Short = &HBF                         ' Timer #2 start.
    Public Const QiERCReset As Short = &H60                             ' ERC signal reset.
    Public Const QiERCSet As Short = &HE0                               ' ERC signal set.
    ' Script1/2/3 setting registers
    Public Const QiSCRCON1Read As Short = &H40                          ' Script1 control queue register READ.
    Public Const QiSCRCON1Write As Short = &HC0                         ' Script1 control queue register WRITE.
    Public Const QiSCRCMD1Read As Short = &H41                          ' Script1 command queue register READ.
    Public Const QiSCRCMD1Write As Short = &HC1                         ' Script1 command queue register WRITE.
    Public Const QiSCRDAT1Read As Short = &H42                          ' Script1 execution data queue register READ.
    Public Const QiSCRDAT1Write As Short = &HC2                         ' Script1 execution data queue register WRITE.
    Public Const QiCQ1Read As Short = &H43                              ' Script1 captured data queue register(top of depth 15 Queue)READ.
    Public Const QiNoOperation_C3 As Short = &HC3                       ' No operation.
    Public Const QiSCRCFG1Read As Short = &H44                          ' Script1 flag control register READ.
    Public Const QiSCRCFG1Write As Short = &HC4                         ' Script1 flag control register WRITE.
    Public Const QiSCRCON2Read As Short = &H45                          ' Script2 control queue register READ.
    Public Const QiSCRCON2Write As Short = &HC5                         ' Script2 control queue register WRITE.
    Public Const QiSCRCMD2Read As Short = &H46                          ' Script2 command queue register READ.
    Public Const QiSCRCMD2Write As Short = &HC6                         ' Script2 command queue register WRITE.
    Public Const QiSCRDAT2Read As Short = &H47                          ' Script2 execution data queue register READ.
    Public Const QiSCRDAT2Write As Short = &HC7                         ' Script2 execution data queue register WRITE.
    Public Const QiCQ2Read As Short = &H48                              ' Script2 captured data queue register(top of depth 15 Queue)READ.
    Public Const QiNoOperation_C8 As Short = &HC8                       ' No operation.
    Public Const QiSCRCFG2Read As Short = &H49                          ' Script2 flag control register READ.
    Public Const QiSCRCFG2Write As Short = &HC9                         ' Script2 flag control register WRITE.
    Public Const QiSCRCON3Read As Short = &H4A                          ' Script3 control register READ.
    Public Const QiSCRCON3Write As Short = &HCA                         ' Script3 control register WRITE.
    Public Const QiSCRCMD3Read As Short = &H4B                          ' Script3 command register READ.
    Public Const QiSCRCMD3Write As Short = &HCB                         ' Script3 command register WRITE.
    Public Const QiSCRDAT3Read As Short = &H4C                          ' Script3 execution data register READ.
    Public Const QiSCRDAT3Write As Short = &HCC                         ' Script3 execution data register WRITE.
    Public Const QiCQ3Read As Short = &H4D                              ' Script3 captured data register READ.
    Public Const QiNoOperation_CD As Short = &HCD                       ' No operation.
    Public Const QiNoOperation_4E As Short = &H4E                       ' No operation.
    Public Const QiNoOperation_CE As Short = &HCE                       ' No operation.
    Public Const QiNoOperation_4F As Short = &H4F                       ' No operation.
    Public Const QiNoOperation_CF As Short = &HCF                       ' [No operation code for script reservation command].
    ' Script4 and Script status setting registers
    Public Const QiSCRCON4Read As Short = &H50                          ' Script4 control register READ.
    Public Const QiSCRCON4Write As Short = &HD0                         ' Script4 control register WRITE.
    Public Const QiSCRCMD4Read As Short = &H51                          ' Script4 command register READ.
    Public Const QiSCRCMD4Write As Short = &HD1                         ' Script4 command register WRITE.
    Public Const QiSCRDAT4Read As Short = &H52                          ' Script4 execution data register READ.
    Public Const QiSCRDAT4Write As Short = &HD2                         ' Script4 execution data register WRITE.
    Public Const QiCQ4Read As Short = &H53                              ' Script4 captured data register READ.
    Public Const QiNoOperation_D3 As Short = &HD3                       ' No operation.
    Public Const QiSCRTGRead As Short = &H54                            ' Target source data setting READ.
    Public Const QiSCRTGWrite As Short = &HD4                           ' Target source data setting WRITE.
    Public Const QiSCRSTAT1Read As Short = &H55                         ' Script status #1 READ.
    Public Const QiNoOperation_D5 As Short = &HD5                       ' No operation.
    Public Const QiSCRSTAT2Read As Short = &H56                         ' Script status #2 READ.
    Public Const QiNoOperation_D6 As Short = &HD6                       ' No operation.
    Public Const QiNoOperation_57 As Short = &H57                       ' No operation.
    Public Const QiINITSQWrite As Short = &HD7                          ' Initialize script queues with target selection.
    Public Const QiNoOperation_58 As Short = &H58                       ' No operation.
    Public Const QiINITCQWrite As Short = &HD8                          ' Initialize captured data queue with target selection.
    Public Const QiSCRMRead As Short = &H59                             ' Set enable mode with target selection READ.
    Public Const QiSCRMWrite As Short = &HD9                            ' Set enable mode with target selection WRITE.
    Public Const QiNoOperation_5A As Short = &H5A                       ' No operation.
    Public Const QiSQ1POP As Short = &HDA                               ' Pop and shift data of script1 queue.
    Public Const QiNoOperation_5B As Short = &H5B                       ' No operation.
    Public Const QiSQ2POP As Short = &HDB                               ' Pop and shift data of script2 queue.
    ' Counter function registers
    Public Const QiCNTLBRead As Short = &H61                            ' Counter lower bound data READ.
    Public Const QiCNTLBWrite As Short = &HE1                           ' Counter lower bound data WRITE.
    Public Const QiCNTUBRead As Short = &H62                            ' Counter upper bound data READ.
    Public Const QiCNTUBWrite As Short = &HE2                           ' Counter upper bound data WRITE.
    Public Const QiCNTCF1Read As Short = &H63                           ' Counter configure #1 READ.
    Public Const QiCNTCF1Write As Short = &HE3                          ' Counter configure #1 WRITE.
    Public Const QiCNTCF2Read As Short = &H64                           ' Counter configure #2 READ.
    Public Const QiCNTCF2Write As Short = &HE4                          ' Counter configure #2 WRITE.
    Public Const QiCNTCF3Read As Short = &H65                           ' Counter configure #3 READ.
    Public Const QiCNTCF3Write As Short = &HE5                          ' Counter configure #3 WRITE.
    Public Const QiCNT1Read As Short = &H66                             ' Counter #1 data READ.
    Public Const QiCNT1Write As Short = &HE6                            ' Counter #1 data WRITE.
    Public Const QiCNT2Read As Short = &H67                             ' Counter #2 data READ.
    Public Const QiCNT2Write As Short = &HE7                            ' Counter #2 data WRITE.
    Public Const QiCNT3Read As Short = &H68                             ' Counter #3 data READ.
    Public Const QiCNT3Write As Short = &HE8                            ' Counter #3 data WRITE.
    Public Const QiCNT4Read As Short = &H69                             ' Counter #4 data READ.
    Public Const QiCNT4Write As Short = &HE9                            ' Counter #4 data WRITE.
    Public Const QiCNT5Read As Short = &H6A                             ' Counter #5 data READ.
    Public Const QiCNT5Write As Short = &HEA                            ' Counter #5 data WRITE.
    Public Const QiCNTC1Read As Short = &H6B                            ' Counter #1 comparator's data READ.
    Public Const QiCNTC1Write As Short = &HEB                           ' Counter #1 comparator's data WRITE.
    Public Const QiCNTC2Read As Short = &H6C                            ' Counter #2 comparator's data READ.
    Public Const QiCNTC2Write As Short = &HEC                           ' Counter #2 comparator's data WRITE.
    Public Const QiCNTC3Read As Short = &H6D                            ' Counter #3 comparator's data READ.
    Public Const QiCNTC3Write As Short = &HED                           ' Counter #3 comparator's data WRITE.
    Public Const QiCNTC4Read As Short = &H6E                            ' Counter #4 comparator's data READ.
    Public Const QiCNTC4Write As Short = &HEE                           ' Counter #4 comparator's data WRITE.
    Public Const QiCNTC5Read As Short = &H6F                            ' Counter #5 comparator's data READ.
    Public Const QiCNTC5Write As Short = &HEF                           ' Counter #5 comparator's data WRITE.
    ' Configure and Status registers
    Public Const QiUCFG1Read As Short = &H70                            ' Configure register #1 READ.
    Public Const QiUCFG1Write As Short = &HF0                           ' Configure register #1 WRITE.
    Public Const QiUCFG2Read As Short = &H71                            ' Configure register #2 READ.
    Public Const QiUCFG2Write As Short = &HF1                           ' Configure register #2 WRITE.
    Public Const QiUCFG3Read As Short = &H72                            ' Configure register #3 READ.
    Public Const QiUCFG3Write As Short = &HF2                           ' Configure register #3 WRITE.
    Public Const QiUCFG4Read As Short = &H73                            ' Configure register #4 READ.
    Public Const QiUCFG4Write As Short = &HF3                           ' Configure register #4 WRITE.
    Public Const QiNoOperation_74 As Short = &H74                       ' No operation.
    Public Const QiNoOperation_F4 As Short = &HF4                       ' No operation.
    Public Const QiNoOperation_75 As Short = &H75                       ' No operation.
    Public Const QiNoOperation_F5 As Short = &HF5                       ' No operation.
    Public Const QiNoOperation_76 As Short = &H76                       ' No operation.
    Public Const QiNoOperation_F6 As Short = &HF6                       ' No operation.
    Public Const QiIMASK1Read As Short = &H77                           ' Interrupt bank#1 mask register READ.
    Public Const QiIMASK1Write As Short = &HF7                          ' Interrupt bank#1 mask register WRITE.
    Public Const QiIMASK2Read As Short = &H78                           ' Interrupt bank#2 mask register READ.
    Public Const QiIMASK2Write As Short = &HF8                          ' Interrupt bank#2 mask register WRITE.
    Public Const QiSTAT1Read As Short = &H79                            ' Status register #1(END STATUS)READ.
    Public Const QiESCLR As Short = &HF9                                ' Status register #1(END STATUS) Clear.
    Public Const QiSTAT2Read As Short = &H7A                            ' Status register #2 READ.
    Public Const QiNoOperation_FA As Short = &HFA                       ' No operation.
    Public Const QiSTAT3Read As Short = &H7B                            ' Status register #3 READ.
    Public Const QiNoOperation_FB As Short = &HFB                       ' No operation.
    Public Const QiSTAT4Read As Short = &H7C                            ' Status register #4 READ.
    Public Const QiNoOperation_FC As Short = &HFC                       ' No operation.
    Public Const QiSTAT5Read As Short = &H7D                            ' Status register #5 READ.
    Public Const QiNoOperation_FD As Short = &HFD                       ' No operation.
    Public Const QiIFLAG1Read As Short = &H7E                           ' Interrupt bank #1 flag READ.
    Public Const QiIFLAG1Clear As Short = &HFE                          ' Interrupt bank #1 flag Clear.
    Public Const QiIFLAG2Read As Short = &H7F                           ' Interrupt bank #2 flag READ.
    Public Const QiIFLAG2Clear As Short = &HFF                          ' Interrupt bank #2 flag Clear.
    
    ' { IP Event Define }
    Public Const EVENT_IPNONE As Short = &H0
    Public Const EVENT_IPDRIVE_END As Short = &H1
    Public Const EVENT_IPPRESETDRIVE_START As Short = &H2
    Public Const EVENT_IPPRESETDRIVE_END As Short = &H3
    Public Const EVENT_IPCONTINOUSDRIVE_START As Short = &H4
    Public Const EVENT_IPCONTINOUSDRIVE_END As Short = &H5
    Public Const EVENT_IPSIGNAL_SEARCH_1_START As Short = &H6
    Public Const EVENT_IPSIGNAL_SEARCH_1_END As Short = &H7
    Public Const EVENT_IPSIGNAL_SEARCH_2_START As Short = &H8
    Public Const EVENT_IPSIGNAL_SEARCH_2_END As Short = &H9
    Public Const EVENT_IPORIGIN_DETECT_START As Short = &HA
    Public Const EVENT_IPORIGIN_DETECT_END As Short = &HB
    Public Const EVENT_IPSPEED_UP As Short = &HC
    Public Const EVENT_IPSPEED_CONST As Short = &HD
    Public Const EVENT_IPSPEED_DOWN As Short = &HE
    Public Const EVENT_IPICL As Short = &HF
    Public Const EVENT_IPICE As Short = &H10
    Public Const EVENT_IPICG As Short = &H11
    Public Const EVENT_IPECL As Short = &H12
    Public Const EVENT_IPECE As Short = &H13
    Public Const EVENT_IPECG As Short = &H14
    Public Const EVENT_IPEPCE As Short = &H15
    Public Const EVENT_IPEPCL As Short = &H16
    Public Const EVENT_IPEPCG As Short = &H17
    Public Const EVENT_IPSPL As Short = &H18
    Public Const EVENT_IPSPE As Short = &H19
    Public Const EVENT_IPSPG As Short = &H1A
    Public Const EVENT_IPSP12L As Short = &H1B
    Public Const EVENT_IPSP12E As Short = &H1C
    Public Const EVENT_IPSP12G As Short = &H1D
    Public Const EVENT_IPSP23L As Short = &H1E
    Public Const EVENT_IPSP23E As Short = &H1F
    Public Const EVENT_IPSP23G As Short = &H20
    Public Const EVENT_IPOBJECT_SPEED As Short = &H21
    Public Const EVENT_IPSS_SPEED As Short = &H22
    Public Const EVENT_IPESTOP As Short = &H23
    Public Const EVENT_IPSSTOP As Short = &H24
    Public Const EVENT_IPPELM As Short = &H25
    Public Const EVENT_IPNELM As Short = &H26
    Public Const EVENT_IPPSLM As Short = &H27
    Public Const EVENT_IPNSLM As Short = &H28
    Public Const EVENT_IPDEVIATION_ERROR As Short = &H29
    Public Const EVENT_IPDATA_ERROR As Short = &H2A
    Public Const EVENT_IPALARM_ERROR As Short = &H2B
    Public Const EVENT_IPESTOP_COMMAND As Short = &H2C
    Public Const EVENT_IPSSTOP_COMMAND As Short = &H2D
    Public Const EVENT_IPESTOP_SIGNAL As Short = &H2E
    Public Const EVENT_IPSSTOP_SIGNAL As Short = &H2F
    Public Const EVENT_IPELM As Short = &H30
    Public Const EVENT_IPSLM As Short = &H31
    Public Const EVENT_IPINPOSITION As Short = &H32
    Public Const EVENT_IPINOUT0_HIGH As Short = &H33
    Public Const EVENT_IPINOUT0_LOW As Short = &H34
    Public Const EVENT_IPINOUT1_HIGH As Short = &H35
    Public Const EVENT_IPINOUT1_LOW As Short = &H36
    Public Const EVENT_IPINOUT2_HIGH As Short = &H37
    Public Const EVENT_IPINOUT2_LOW As Short = &H38
    Public Const EVENT_IPINOUT3_HIGH As Short = &H39
    Public Const EVENT_IPINOUT3_LOW As Short = &H3A
    Public Const EVENT_IPINOUT4_HIGH As Short = &H3B
    Public Const EVENT_IPINOUT4_LOW As Short = &H3C
    Public Const EVENT_IPINOUT5_HIGH As Short = &H3D
    Public Const EVENT_IPINOUT5_LOW As Short = &H3E
    Public Const EVENT_IPINOUT6_HIGH As Short = &H3F
    Public Const EVENT_IPINOUT6_LOW As Short = &H40
    Public Const EVENT_IPINOUT7_HIGH As Short = &H41
    Public Const EVENT_IPINOUT7_LOW As Short = &H42
    Public Const EVENT_IPINOUT8_HIGH As Short = &H43
    Public Const EVENT_IPINOUT8_LOW As Short = &H44
    Public Const EVENT_IPINOUT9_HIGH As Short = &H45
    Public Const EVENT_IPINOUT9_LOW As Short = &H46
    Public Const EVENT_IPINOUT10_HIGH As Short = &H47
    Public Const EVENT_IPINOUT10_LOW As Short = &H48
    Public Const EVENT_IPINOUT11_HIGH As Short = &H49
    Public Const EVENT_IPINOUT11_LOW As Short = &H4A
    Public Const EVENT_IPSENSOR_DRIVE1_START As Short = &H4B
    Public Const EVENT_IPSENSOR_DRIVE1_END As Short = &H4C
    Public Const EVENT_IPSENSOR_DRIVE2_START As Short = &H4D
    Public Const EVENT_IPSENSOR_DRIVE2_END As Short = &H4E
    Public Const EVENT_IPSENSOR_DRIVE3_START As Short = &H4F
    Public Const EVENT_IPSENSOR_DRIVE3_END As Short = &H50
    Public Const EVENT_IP1STCOUNTER_NDATA_CLEAR As Short = &H51
    Public Const EVENT_IP2NDCOUNTER_NDATA_CLEAR As Short = &H52
    Public Const EVENT_IPMARK_SIGNAL_HIGH As Short = &H53
    Public Const EVENT_IPMARK_SIGNAL_LOW As Short = &H54
    Public Const EVENT_IPSOFTWARE_PLIMIT As Short = &H55
    Public Const EVENT_IPSOFTWARE_NLIMIT As Short = &H56
    Public Const EVENT_IPSOFTWARE_LIMIT As Short = &H57
    Public Const EVENT_IPTRIGGER_ENABLE As Short = &H58
    Public Const EVENT_IPINT_GEN_SOURCE As Short = &H59
    Public Const EVENT_IPINT_GEN_CMDF9 As Short = &H5A
    Public Const EVENT_IPPRESETDRIVE_TRI_START As Short = &H5B
    Public Const EVENT_IPBUSY_HIGH As Short = &H5C
    Public Const EVENT_IPBUSY_LOW As Short = &H5D
    Public Const EVENT_IPLINP_START As Short = &H5E
    Public Const EVENT_IPLINP_END As Short = &H5F
    Public Const EVENT_IPCINP_START As Short = &H60
    Public Const EVENT_IPCINP_END As Short = &H61
    Public Const EVENT_IPPINP_START As Short = &H62
    Public Const EVENT_IPPINP_END As Short = &H63
    Public Const EVENT_IPPDATA_Q_EMPTY As Short = &H64
    Public Const EVENT_IPS_C_INTERNAL_COMMAND_Q_EMPTY As Short = &H65
    Public Const EVENT_IPS_C_INTERNAL_COMMAND_Q_FULL As Short = &H66
    Public Const EVENT_IPxSYNC_ACTIVATED As Short = &H67
    Public Const EVENT_IPySYNC_ACTIVATED As Short = &H68
    Public Const EVENT_IPINTERRUPT_GENERATED As Short = &H69
    Public Const EVENT_IPINP_START As Short = &H6A
    Public Const EVENT_IPINP_END As Short = &H6B
    Public Const EVENT_IPALGEBRIC_RESULT_BIT0 As Short = &H6C
    Public Const EVENT_IPALGEBRIC_RESULT_BIT1 As Short = &H6D
    Public Const EVENT_IPALGEBRIC_RESULT_BIT2 As Short = &H6E
    Public Const EVENT_IPALGEBRIC_RESULT_BIT3 As Short = &H6F
    Public Const EVENT_IPALGEBRIC_RESULT_BIT4 As Short = &H70
    Public Const EVENT_IPALGEBRIC_RESULT_BIT5 As Short = &H71
    Public Const EVENT_IPALGEBRIC_RESULT_BIT6 As Short = &H72
    Public Const EVENT_IPALGEBRIC_RESULT_BIT7 As Short = &H73
    Public Const EVENT_IPALGEBRIC_RESULT_BIT8 As Short = &H74
    Public Const EVENT_IPALGEBRIC_RESULT_BIT9 As Short = &H75
    Public Const EVENT_IPALGEBRIC_RESULT_BIT10 As Short = &H76
    Public Const EVENT_IPALGEBRIC_RESULT_BIT11 As Short = &H77
    Public Const EVENT_IPALGEBRIC_RESULT_BIT12 As Short = &H78
    Public Const EVENT_IPALGEBRIC_RESULT_BIT13 As Short = &H79
    Public Const EVENT_IPALGEBRIC_RESULT_BIT14 As Short = &H7A
    Public Const EVENT_IPALGEBRIC_RESULT_BIT15 As Short = &H7B
    Public Const EVENT_IPALGEBRIC_RESULT_BIT16 As Short = &H7C
    Public Const EVENT_IPALGEBRIC_RESULT_BIT17 As Short = &H7D
    Public Const EVENT_IPALGEBRIC_RESULT_BIT18 As Short = &H7E
    Public Const EVENT_IPALGEBRIC_RESULT_BIT19 As Short = &H7F
    Public Const EVENT_IPALGEBRIC_RESULT_BIT20 As Short = &H80
    Public Const EVENT_IPALGEBRIC_RESULT_BIT21 As Short = &H81
    Public Const EVENT_IPALGEBRIC_RESULT_BIT22 As Short = &H82
    Public Const EVENT_IPALGEBRIC_RESULT_BIT23 As Short = &H83
    Public Const EVENT_IPALGEBRIC_RESULT_BIT24 As Short = &H84
    Public Const EVENT_IPALGEBRIC_RESULT_BIT25 As Short = &H85
    Public Const EVENT_IPALGEBRIC_RESULT_BIT26 As Short = &H86
    Public Const EVENT_IPALGEBRIC_RESULT_BIT27 As Short = &H87
    Public Const EVENT_IPALGEBRIC_RESULT_BIT28 As Short = &H88
    Public Const EVENT_IPALGEBRIC_RESULT_BIT29 As Short = &H89
    Public Const EVENT_IPALGEBRIC_RESULT_BIT30 As Short = &H8A
    Public Const EVENT_IPALGEBRIC_RESULT_BIT31 As Short = &H8B
    Public Const EVENT_IPCOMPARE_RESULT_BIT0 As Short = &H8C
    Public Const EVENT_IPCOMPARE_RESULT_BIT1 As Short = &H8D
    Public Const EVENT_IPCOMPARE_RESULT_BIT2 As Short = &H8E
    Public Const EVENT_IPCOMPARE_RESULT_BIT3 As Short = &H8F
    Public Const EVENT_IPCOMPARE_RESULT_BIT4 As Short = &H90
    Public Const EVENT_IPON_INTERPOLATION As Short = &H91
    Public Const EVENT_IPON_LINEAR_INTERPOLATION As Short = &H92
    Public Const EVENT_IPON_CIRCULAR_INTERPOLATION As Short = &H93
    Public Const EVENT_IPON_PATTERN_INTERPOLATION As Short = &H94
    Public Const EVENT_IPNONE_95 As Short = &H95
    Public Const EVENT_IPL_C_INP_Q_EMPTY As Short = &H96
    Public Const EVENT_IPL_C_INP_Q_LESS_4 As Short = &H97
    Public Const EVENT_IPP_INP_Q_EMPTY As Short = &H98
    Public Const EVENT_IPP_INP_Q_LESS_4 As Short = &H99
    Public Const EVENT_IPINTERPOLATION_PAUSED As Short = &H9A
    Public Const EVENT_IPP_INP_END_BY_END_PATTERN As Short = &H9B
    Public Const EVENT_IPARITHMETIC_DATA_SEL As Short = &HEE
    Public Const EVENT_IPEXECUTION_ALWAYS As Short = &HFF
    
    '{ QI Event Define }
    Public Const EVENT_QINOOP As Short = &H0                            ' No operation.
    Public Const EVENT_QIDRVEND As Short = &H1                          ' Drive end event(inposition function excluded).
    Public Const EVENT_QIDECEL As Short = &H2                           ' Deceleration state.
    Public Const EVENT_QICONST As Short = &H3                           ' Constant speed state.
    Public Const EVENT_QIACCEL As Short = &H4                           ' Acceleration state.
    Public Const EVENT_QICNT1L As Short = &H5                           ' Counter1 < Comparater1 state.
    Public Const EVENT_QICNT1E As Short = &H6                           ' Counter1 As Short = Comparater1 state.
    Public Const EVENT_QICNT1G As Short = &H7                           ' Counter1 > Comparater1 state.
    Public Const EVENT_QICNT1LE As Short = &H8                          ' Counter1 ¡Â Comparater1 state.
    Public Const EVENT_QICNT1GE As Short = &H9                          ' Counter1 ¡Ã Comparater1 state.
    Public Const EVENT_QICNT1EUP As Short = &HA                         ' Counter1 As Short = Comparater1 event during counting up.
    Public Const EVENT_QICNT1EDN As Short = &HB                         ' Counter1 As Short = Comparater1 event during counting down.
    Public Const EVENT_QICNT1BND As Short = &HC                         ' Counter1 is same with boundary value.
    Public Const EVENT_QICNT2L As Short = &HD                           ' Counter2 < Comparater2 state.
    Public Const EVENT_QICNT2E As Short = &HE                           ' Counter2 As Short = Comparater2 state.
    Public Const EVENT_QICNT2G As Short = &HF                           ' Counter2 > Comparater2 state.
    Public Const EVENT_QICNT2LE As Short = &H10                         ' Counter2 ¡Â Comparater2 state.
    Public Const EVENT_QICNT2GE As Short = &H11                         ' Counter2 ¡Ã Comparater2 state.
    Public Const EVENT_QICNT2EUP As Short = &H12                        ' Counter2 As Short = Comparater2 event during counting up.
    Public Const EVENT_QICNT2EDN As Short = &H13                        ' Counter2 As Short = Comparater2 event during counting down.
    Public Const EVENT_QICNT2BND As Short = &H14                        ' Counter2 is same with boundary value.
    Public Const EVENT_QICNT3L As Short = &H15                          ' Counter3 < Comparater3 state.
    Public Const EVENT_QICNT3E As Short = &H16                          ' Counter3 As Short = Comparater3 state.
    Public Const EVENT_QICNT3G As Short = &H17                          ' Counter3 > Comparater3 state.
    Public Const EVENT_QICNT3LE As Short = &H18                         ' Counter3 ¡Â Comparater3 state.
    Public Const EVENT_QICNT3GE As Short = &H19                         ' Counter3 ¡Ã Comparater3 state.
    Public Const EVENT_QICNT3EUP As Short = &H1A                        ' Counter3 As Short = Comparater3 event during counting up.
    Public Const EVENT_QICNT3EDN As Short = &H1B                        ' Counter3 As Short = Comparater3 event during counting down.
    Public Const EVENT_QICNT3BND As Short = &H1C                        ' Counter3 is same with boundary value.
    Public Const EVENT_QICNT4L As Short = &H1D                          ' Counter4 < Comparater4 state.
    Public Const EVENT_QICNT4E As Short = &H1E                          ' Counter4 As Short = Comparater4 state.
    Public Const EVENT_QICNT4G As Short = &H1F                          ' Counter4 > Comparater4 state.
    Public Const EVENT_QICNT4LE As Short = &H20                         ' Counter4 ¡Â Comparater4 state.
    Public Const EVENT_QICNT4GE As Short = &H21                         ' Counter4 ¡Ã Comparater4 state.
    Public Const EVENT_QICNT4EUP As Short = &H22                        ' Counter4 As Short = Comparater4 event during counting up.
    Public Const EVENT_QICNT4EDN As Short = &H23                        ' Counter4 As Short = Comparater4 event during counting down.
    Public Const EVENT_QICNT4BND As Short = &H24                        ' Counter4 is same with boundary value.
    Public Const EVENT_QICNT5L As Short = &H25                          ' Counter5 < Comparater5 state.
    Public Const EVENT_QICNT5E As Short = &H26                          ' Counter5 As Short = Comparater5 state.
    Public Const EVENT_QICNT5G As Short = &H27                          ' Counter5 > Comparater5 state.
    Public Const EVENT_QICNT5LE As Short = &H28                         ' Counter5 ¡Â Comparater5 state.
    Public Const EVENT_QICNT5GE As Short = &H29                         ' Counter5 ¡Ã Comparater5 state.
    Public Const EVENT_QICNT5EUP As Short = &H2A                        ' Counter5 As Short = Comparater5 event during counting up.
    Public Const EVENT_QICNT5EDN As Short = &H2B                        ' Counter5 As Short = Comparater5 event during counting down.
    Public Const EVENT_QICNT5BND As Short = &H2C                        ' Counter5 is same with boundary value.
    Public Const EVENT_QIDEVL As Short = &H2D                           ' DEVIATION value < Comparater4 state.
    Public Const EVENT_QIDEVE As Short = &H2E                           ' DEVIATION value As Short = Comparater4 state.
    Public Const EVENT_QIDEVG As Short = &H2F                           ' DEVIATION value > Comparater4 state.
    Public Const EVENT_QIDEVLE As Short = &H30                          ' DEVIATION value ¡Â Comparater4 state.
    Public Const EVENT_QIDEVGE As Short = &H31                          ' DEVIATION value ¡Ã Comparater4 state.
    Public Const EVENT_QIPELM As Short = &H32                           ' PELM input signal is activated state.
    Public Const EVENT_QINELM As Short = &H33                           ' NELM input signal is activated state.
    Public Const EVENT_QIPSLM As Short = &H34                           ' PSLM input signal is activated state.
    Public Const EVENT_QINSLM As Short = &H35                           ' NSLM input signal is activated state.
    Public Const EVENT_QIALARM As Short = &H36                          ' ALAMR input signal is activated state.
    Public Const EVENT_QIINPOS As Short = &H37                          ' INPOSITION input signal ia activated state.
    Public Const EVENT_QIESTOP As Short = &H38                          ' ESTOP input signal is activated state.
    Public Const EVENT_QIORG As Short = &H39                            ' ORG input signal is activated state.
    Public Const EVENT_QIZ_PHASE As Short = &H3A                        ' Z_PHASE input signal is activated state.
    Public Const EVENT_QIECUP As Short = &H3B                           ' ECUP input signal is high level state.
    Public Const EVENT_QIECDN As Short = &H3C                           ' ECDN input signal is high level state.
    Public Const EVENT_QIEXPP As Short = &H3D                           ' EXPP input signal is high level state.
    Public Const EVENT_QIEXMP As Short = &H3E                           ' EXMP input signal is high level state.
    Public Const EVENT_QISQSTR1 As Short = &H3F                         ' SYNC Start1 input signal is activated state(activated).
    Public Const EVENT_QISQSTR2 As Short = &H40                         ' SYNC Start2 input signal is activated state(activated).
    Public Const EVENT_QISQSTP1 As Short = &H41                         ' SYNC STOP1 input signal is activated state(activated).
    Public Const EVENT_QISQSTP2 As Short = &H42                         ' SYNC STOP2 input signal is activated state(activated).
    Public Const EVENT_QIALARMS As Short = &H43                         ' At least one alarm signal of each axis is activated state.
    Public Const EVENT_QIUIO0 As Short = &H44                           ' UIO0 data is high state.
    Public Const EVENT_QIUIO1 As Short = &H45                           ' UIO1 data is high state.
    Public Const EVENT_QIUIO2 As Short = &H46                           ' UIO2 data is high state.
    Public Const EVENT_QIUIO3 As Short = &H47                           ' UIO3 data is high state.
    Public Const EVENT_QIUIO4 As Short = &H48                           ' UIO4 data is high state.
    Public Const EVENT_QIUIO5 As Short = &H49                           ' UIO5 data is high state.
    Public Const EVENT_QIUIO6 As Short = &H4A                           ' UIO6 data is high state.
    Public Const EVENT_QIUIO7 As Short = &H4B                           ' UIO7 data is high state.
    Public Const EVENT_QIUIO8 As Short = &H4C                           ' UIO8 data is high state.
    Public Const EVENT_QIUIO9 As Short = &H4D                           ' UIO9 data is high state.
    Public Const EVENT_QIUIO10 As Short = &H4E                          ' UIO10 data is high state.
    Public Const EVENT_QIUIO11 As Short = &H4F                          ' UIO11 data is high state.
    Public Const EVENT_QIERC As Short = &H50                            ' ERC output is activated.
    Public Const EVENT_QITRG As Short = &H51                            ' TRIGGER signal is activated.
    Public Const EVENT_QIPREQI0 As Short = &H52                         ' Previous queue data index 0 bit is high state.
    Public Const EVENT_QIPREQI1 As Short = &H53                         ' Previous queue data index 1 bit is high state.
    Public Const EVENT_QIPREQI2 As Short = &H54                         ' Previous queue data index 2 bit is high state.
    Public Const EVENT_QIPREQZ As Short = &H55                          ' Previous queue is empty state.
    Public Const EVENT_QIPREQF As Short = &H56                          ' Previous queue is full state.
    Public Const EVENT_QIMPGE1 As Short = &H57                          ' MPG first stage is overflowed state.
    Public Const EVENT_QIMPGE2 As Short = &H58                          ' MPG second stage is overflowed state.
    Public Const EVENT_QIMPGE3 As Short = &H59                          ' MPG third stage is overflowed state.
    Public Const EVENT_QIMPGERR As Short = &H5A                         ' MPG all state is overflowed state.
    Public Const EVENT_QITRGCNT0 As Short = &H5B                        ' TRIGGER queue index bit 0 is high state.
    Public Const EVENT_QITRGCNT1 As Short = &H5C                        ' TRIGGER queue index bit 1 is high state.
    Public Const EVENT_QITRGCNT2 As Short = &H5D                        ' TRIGGER queue index bit 2 is high state.
    Public Const EVENT_QITRGCNT3 As Short = &H5E                        ' TRIGGER queue index bit 3 is high state.
    Public Const EVENT_QITRGQEPT As Short = &H5F                        ' TRIGGER queue is empty state.
    Public Const EVENT_QITRGQFULL As Short = &H60                       ' TRIGGER queue is full state.
    Public Const EVENT_QIDPAUSE As Short = &H61                         ' Drive paused state.
    Public Const EVENT_QIESTOPEXE As Short = &H62                       ' Emergency stop occurred
    Public Const EVENT_QISSTOPEXE As Short = &H63                       ' Slowdown stop occurred
    Public Const EVENT_QIPLMTSTOP As Short = &H64                       ' Limit stop event occurred during positive driving.
    Public Const EVENT_QINLMTSTOP As Short = &H65                       ' Limit stop event occurred during negative driving.
    Public Const EVENT_QIOPLMTSTOP As Short = &H66                      ' Optional limit stop event occurred during positive driving.
    Public Const EVENT_QIONLMTSTOP As Short = &H67                      ' Optional limit stop event occurred during negative driving.
    Public Const EVENT_QIPSWESTOP As Short = &H68                       ' Software emergency limit stop event occurred.(CW)
    Public Const EVENT_QINSWESTOP As Short = &H69                       ' Software emergency limit stop event occurred.(CCW)
    Public Const EVENT_QIPSWSSTOP As Short = &H6A                       ' Software slowdown limit stop event occurred.(CW)
    Public Const EVENT_QINSWSSTOP As Short = &H6B                       ' Software slowdown limit stop event occurred.(CCW)
    Public Const EVENT_QIALMSTOP As Short = &H6C                        ' Emergency stop event occurred by alarm signal function.
    Public Const EVENT_QIESTOPSTOP As Short = &H6D                      ' Emergency stop event occurred by estop signal function.
    Public Const EVENT_QIESTOPCMD As Short = &H6E                       ' Emergency stop event occurred by command.
    Public Const EVENT_QISSTOPCMD As Short = &H6F                       ' Slowdown stop event occurred by command.
    Public Const EVENT_QIALLSTCMD As Short = &H70                       ' Emergency stop event occurred by all stop command.
    Public Const EVENT_QISYSTOP1 As Short = &H71                        ' SYNC stop1 event occurred.
    Public Const EVENT_QISYSTOP2 As Short = &H72                        ' SYNC stop2 event occurred.
    Public Const EVENT_QIENCODERR As Short = &H73                       ' Encoder input error event occurred.
    Public Const EVENT_QIMPGOVERFLOW As Short = &H74                    ' MPG input error event occurred.
    Public Const EVENT_QIORGOK As Short = &H75                          ' Original drive is executed successfully.
    Public Const EVENT_QISSCHOK As Short = &H76                         ' Signal search drive is executed successfully.
    Public Const EVENT_QIUIO0LOW As Short = &H77                        ' UIO0 data is low state.
    Public Const EVENT_QIUIO1LOW As Short = &H78                        ' UIO1 data is low state.
    Public Const EVENT_QIUIO2LOW As Short = &H79                        ' UIO2 data is low state.
    Public Const EVENT_QIUIO3LOW As Short = &H7A                        ' UIO3 data is low state.
    Public Const EVENT_QIUIO4LOW As Short = &H7B                        ' UIO4 data is low state.
    Public Const EVENT_QIUIO5LOW As Short = &H7C                        ' UIO5 data is low state.
    Public Const EVENT_QIUIO6LOW As Short = &H7D                        ' UIO6 data is low state.
    Public Const EVENT_QIUIO7LOW As Short = &H7E                        ' UIO7 data is low state.
    Public Const EVENT_QIUIO8LOW As Short = &H7F                        ' UIO8 data is low state.
    Public Const EVENT_QIUIO9LOW As Short = &H80                        ' UIO9 data is low state.
    Public Const EVENT_QIUIO10LOW As Short = &H81                       ' UIO10 data is low state.
    Public Const EVENT_QIUIO11LOW As Short = &H82                       ' UIO11 data is low state.
    Public Const EVENT_QIUIO0RISING As Short = &H83                     ' UIO0 rising edge event occurred.
    Public Const EVENT_QIUIO1RISING As Short = &H84                     ' UIO1 rising edge event occurred.
    Public Const EVENT_QIUIO2RISING As Short = &H85                     ' UIO2 rising edge event occurred.
    Public Const EVENT_QIUIO3RISING As Short = &H86                     ' UIO3 rising edge event occurred.
    Public Const EVENT_QIUIO4RISING As Short = &H87                     ' UIO4 rising edge event occurred.
    Public Const EVENT_QIUIO5RISING As Short = &H88                     ' UIO5 rising edge event occurred.
    Public Const EVENT_QIUIO6RISING As Short = &H89                     ' UIO6 rising edge event occurred.
    Public Const EVENT_QIUIO7RISING As Short = &H8A                     ' UIO7 rising edge event occurred.
    Public Const EVENT_QIUIO8RISING As Short = &H8B                     ' UIO8 rising edge event occurred.
    Public Const EVENT_QIUIO9RISING As Short = &H8C                     ' UIO9 rising edge event occurred.
    Public Const EVENT_QIUIO10RISING As Short = &H8D                    ' UIO10 rising edge event occurred.
    Public Const EVENT_QIUIO11RISING As Short = &H8E                    ' UIO11 rising edge event occurred.
    Public Const EVENT_QIUIO0FALLING As Short = &H8F                    ' UIO0 falling edge event occurred.
    Public Const EVENT_QIUIO1FALLING As Short = &H90                    ' UIO1 falling edge event occurred.
    Public Const EVENT_QIUIO2FALLING As Short = &H91                    ' UIO2 falling edge event occurred.
    Public Const EVENT_QIUIO3FALLING As Short = &H92                    ' UIO3 falling edge event occurred.
    Public Const EVENT_QIUIO4FALLING As Short = &H93                    ' UIO4 falling edge event occurred.
    Public Const EVENT_QIUIO5FALLING As Short = &H94                    ' UIO5 falling edge event occurred.
    Public Const EVENT_QIUIO6FALLING As Short = &H95                    ' UIO6 falling edge event occurred.
    Public Const EVENT_QIUIO7FALLING As Short = &H96                    ' UIO7 falling edge event occurred.
    Public Const EVENT_QIUIO8FALLING As Short = &H97                    ' UIO8 falling edge event occurred.
    Public Const EVENT_QIUIO9FALLING As Short = &H98                    ' UIO9 falling edge event occurred.
    Public Const EVENT_QIUIO10FALLING As Short = &H99                   ' UIO10 falling edge event occurred.
    Public Const EVENT_QIUIO11FALLING As Short = &H9A                   ' UIO11 falling edge event occurred.
    Public Const EVENT_QIDRVSTR As Short = &H9B                         ' Drive started.
    Public Const EVENT_QIDNSTR As Short = &H9C                          ' Speed down event occurred.
    Public Const EVENT_QICOSTR As Short = &H9D                          ' Constant speed event occurred.
    Public Const EVENT_QIUPSTR As Short = &H9E                          ' Speed up event occurred.
    Public Const EVENT_QICONTISTR As Short = &H9F                       ' Continuous drive started.
    Public Const EVENT_QIPRESETSTR As Short = &HA0                      ' Preset drive started.
    Public Const EVENT_QIMPGSTR As Short = &HA1                         ' MPG drive started.
    Public Const EVENT_QIORGSTR As Short = &HA2                         ' Original drive started.
    Public Const EVENT_QISSCHSTR As Short = &HA3                        ' Signal search drive started.
    Public Const EVENT_QIPATHSTR As Short = &HA4                        ' Interpolation drive started.
    Public Const EVENT_QISLAVESTR As Short = &HA5                       ' Slave drive started.
    Public Const EVENT_QICCWSTR As Short = &HA6                         ' CCW direction drive started.
    Public Const EVENT_QIINPWAIT As Short = &HA7                        ' Inposition wait event occurred.
    Public Const EVENT_QILINSTR As Short = &HA8                         ' Linear drive stated.
    Public Const EVENT_QICIRSTR As Short = &HA9                         ' Circular drive started.
    Public Const EVENT_QIDRVENDII As Short = &HAA                       ' Drive stopped.(Inposition state included)
    Public Const EVENT_QIDNEND As Short = &HAB                          ' Speed down end event occurred.
    Public Const EVENT_QICOEND As Short = &HAC                          ' Constant speed end event occurred.
    Public Const EVENT_QIUPEND As Short = &HAD                          ' Speed up end event occurred.
    Public Const EVENT_QICONTIEND As Short = &HAE                       ' Continuous drive ended.
    Public Const EVENT_QIPRESETEND As Short = &HAF                      ' Preset drive ended.
    Public Const EVENT_QIMPGEND As Short = &HB0                         ' MPG drive ended.
    Public Const EVENT_QIORGEND As Short = &HB1                         ' Original drive ended.
    Public Const EVENT_QISSCHEND As Short = &HB2                        ' Signal search drive ended.
    Public Const EVENT_QIPATHEND As Short = &HB3                        ' Interpolation drive ended.
    Public Const EVENT_QISLAVEEND As Short = &HB4                       ' Slave drive ended.
    Public Const EVENT_QICCWEND As Short = &HB5                         ' CCW direction drive ended.
    Public Const EVENT_QIINPEND As Short = &HB6                         ' Escape from Inposition waiting.
    Public Const EVENT_QILINEND As Short = &HB7                         ' Linear drive ended.
    Public Const EVENT_QICIREND As Short = &HB8                         ' Circular drive ended.
    Public Const EVENT_QIBUSY As Short = &HB9                           ' During driving state.
    Public Const EVENT_QINBUSY As Short = &HBA                          ' During not driving state.
    Public Const EVENT_QITMR1EX As Short = &HBB                         ' Timer1 expired event.
    Public Const EVENT_QITMR2EX As Short = &HBC                         ' Timer2 expired event.
    Public Const EVENT_QIDRVENDIII As Short = &HBD                      ' Drive(that interrupt enable bit is set to high) end event
    Public Const EVENT_QIERROR As Short = &HBE                          ' Error stop occurred.
    Public Const EVENT_QINOP As Short = &HBF                            ' NOP.
    Public Const EVENT_QIALWAYS As Short = &HFF                         ' Always Generate.
    
    '{ QI Register Define }
    Public Const QI_SCR_REG1 As Short = &H1
    Public Const QI_SCR_REG2 As Short = &H2
    Public Const QI_SCR_REG3 As Short = &H3
    Public Const QI_SCR_REG4 As Short = &H4
    Public Const QI_OPERATION_ONCE_RUN As Short = &H0                   ' bit 24 OFF
    Public Const QI_OPERATION_CONTINUE_RUN As Long = &H1000000          ' bit 24 ON
    Public Const QI_INPUT_DATA_FROM_SCRIPT_DATA As Short = &H0          ' bit 23 OFF
    Public Const QI_INPUT_DATA_FROM_TARGET_REG As Long = &H800000       ' bit 23 ON
    Public Const QI_INTERRUPT_GEN_ENABLE As Long = &H400000             ' bit 22 ON
    Public Const QI_INTERRUPT_GEN_DISABLE As Short = &H0                ' bit 22 OFF
    Public Const QI_OPERATION_EVENT_NONE As Short = &H0                 ' bit 21=OFF, 20=OFF
    Public Const QI_OPERATION_EVENT_AND As Long = &H100000              ' bit 21=OFF, 20=ON
    Public Const QI_OPERATION_EVENT_OR As Long = &H200000               ' bit 21=ON,  20=OFF
    Public Const QI_OPERATION_EVENT_XOR As Long = &H300000              ' bit 21=ON,  20=ON
    
    Function QI_SND_EVENT_AXIS(ByVal Axis As Long) As Long              ' bit 19~18 (00:X, 01:Y, 10:Z, 11:U)
        QI_SND_EVENT_AXIS = ((Axis Mod 4) * (2 ^ 18))
    End Function

    Function QI_FST_EVENT_AXIS(ByVal Axis As Long) As Long              ' bit 17~16 (00:X, 01:Y, 10:Z, 11:U)
        QI_FST_EVENT_AXIS = ((Axis Mod 4) * (2 ^ 16))
    End Function

    Function QI_OPERATION_EVENT_2(ByVal Event1 As Long) As Long         ' bit 15..8
        QI_OPERATION_EVENT_2 = ((Event1 And &HFF) * (2 ^ 8))
    End Function

    Function QI_OPERATION_EVENT_1(ByVal Event1 As Long) As Long         ' bit 7..0
        QI_OPERATION_EVENT_1 = (Event1 And &HFF)
    End Function

    Function QI_OPERATION_COMMAND(ByVal Command As Long, ByVal Axis As Long) As Long
        QI_OPERATION_COMMAND = ((Command And &HFF) * (2 ^ ((Axis Mod 4) * 8)))
    End Function
    
End Module
