#ifndef __AXT_DAXC_H__
#define __AXT_DAXC_H__

//#include "AXHS.h"
#include "../../AXL(Library)/C, C++/AXHS.h"

typedef DWORD    PASCAL EXPORT funcAxcInfoIsCNTModule(DWORD *upStatus);
typedef DWORD    PASCAL EXPORT funcAxcInfoGetModuleNo(long lBoardNo, long lModulePos, long *lpModuleNo);
typedef DWORD    PASCAL EXPORT funcAxcInfoGetModuleCount(long *lpModuleCount);
typedef DWORD    PASCAL EXPORT funcAxcInfoGetChannelCount(long lModuleNo, long *lpCount);
typedef DWORD    PASCAL EXPORT funcAxcInfoGetTotalChannelCount(long *lpChannelCount);   
typedef DWORD    PASCAL EXPORT funcAxcInfoGetModule(long lModuleNo, long *lpBoardNo, long *lpModulePos, DWORD *upModuleID);
typedef DWORD    PASCAL EXPORT funcAxcInfoGetModuleStatus(long lModuleNo);
typedef DWORD    PASCAL EXPORT funcAxcInfoGetFirstChannelNoOfModuleNo(long lModuleNo, long *lpChannelNo);
typedef DWORD    PASCAL EXPORT funcAxcSignalSetEncInputMethod(long lChannelNo, DWORD dwMethod);
typedef DWORD    PASCAL EXPORT funcAxcSignalGetEncInputMethod(long lChannelNo, DWORD* dwpUpMethod);
typedef DWORD    PASCAL EXPORT funcAxcSignalSetCaptureFunction(long lChannelNo, DWORD dwCapturePol);
typedef DWORD    PASCAL EXPORT funcAxcSignalGetCaptureFunction(long lChannelNo, DWORD* dwpCapturePol);
typedef DWORD    PASCAL EXPORT funcAxcSignalGetCapturePos(long lChannelNo, double* dbpCapturePos);
typedef DWORD    PASCAL EXPORT funcAxcSignalSetEncReverse(long lChannelNo, DWORD dwReverse);
typedef DWORD    PASCAL EXPORT funcAxcSignalGetEncReverse(long lChannelNo, DWORD* dwpReverse);
typedef DWORD    PASCAL EXPORT funcAxcSignalSetEncSource(long lChannelNo, DWORD dwSource);
typedef DWORD    PASCAL EXPORT funcAxcSignalGetEncSource(long lChannelNo, DWORD* dwpSource);
typedef DWORD    PASCAL EXPORT funcAxcSignalWriteOutput(long lChannelNo, DWORD dwOutput);
typedef DWORD    PASCAL EXPORT funcAxcSignalReadOutput(long lChannelNo, DWORD* dwpOutput);
typedef DWORD    PASCAL EXPORT funcAxcSignalWriteOutputBit(long lChannelNo, long lBitNo, DWORD uOnOff);
typedef DWORD    PASCAL EXPORT funcAxcSignalReadOutputBit(long lChannelNo,long lBitNo, DWORD *upOnOff);
typedef DWORD    PASCAL EXPORT funcAxcSignalReadInput(long lChannelNo, DWORD* dwpInput);
typedef DWORD    PASCAL EXPORT funcAxcSignalReadInputBit(long lChannelNo, long lBitNo, DWORD *upOnOff);
typedef DWORD    PASCAL EXPORT funcAxcStatusGetActPos(long lChannelNo, double* dbpActPos);
typedef DWORD    PASCAL EXPORT funcAxcStatusSetActPos(long lChannelNo, double dbActPos);
typedef DWORD    PASCAL EXPORT funcAxcStatusGetChannel(long lChannelNo, DWORD* dwpChannelStatus);
typedef DWORD    PASCAL EXPORT funcAxcMotSetMoveUnitPerPulse(long lChannelNo, double dMoveUnitPerPulse);
typedef DWORD    PASCAL EXPORT funcAxcMotGetMoveUnitPerPulse(long lChannelNo, double* dpMoveUnitPerPuls);
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetFunction(long lChannelNo, DWORD dwMode);
typedef DWORD    PASCAL EXPORT funcAxcTriggerGetFunction(long lChannelNo, DWORD* dwpMode);
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetNotchPos(long lChannelNo, double dbLowerPos, double dbUpperPos);
typedef DWORD    PASCAL EXPORT funcAxcTriggerGetNotchPos(long lChannelNo, double* dbpLowerPos, double* dbpUpperPos);
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetOutput(long lChannelNo, DWORD dwOutVal);
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetNotchPos(long lChannelNo, double dbLowerPos, double dbUpperPos);
typedef DWORD    PASCAL EXPORT funcAxcTriggerGetNotchPos(long lChannelNo, double* dbpLowerPos, double* dbpUpperPos);
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetBlockLowerPos(long lChannelNo, double dLowerPosition);
typedef DWORD    PASCAL EXPORT funcAxcTriggerGetBlockLowerPos(long lChannelNo, double* dpLowerPosition);
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetBlockUpperPos(long lChannelNo, double dUpperPosition);
typedef DWORD    PASCAL EXPORT funcAxcTriggerGetBlockUpperPos(long lChannelNo, double* dpUpperrPosition);
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetPosPeriod(long lChannelNo, double dPeriod);
typedef DWORD    PASCAL EXPORT funcAxcTriggerGetPosPeriod(long lChannelNo, double* dpPeriod);
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetDirectionCheck(long lChannelNo, DWORD dwDirection);
typedef DWORD    PASCAL EXPORT funcAxcTriggerGetDirectionCheck(long lChannelNo, DWORD* dwpDirection);
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetBlock(long lChannelNo, double dLower, double dUpper, double dABSod);
typedef DWORD    PASCAL EXPORT funcAxcTriggerGetBlock(long lChannelNo, double *dpLower, double *dpUpper, double *dpABSod);
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetTime(long lChannelNo, double dTrigTime);
typedef DWORD    PASCAL EXPORT funcAxcTriggerGetTime(long lChannelNo, double* dpTrigTime);
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetLevel(long lChannelNo, DWORD dwLevel);
typedef DWORD    PASCAL EXPORT funcAxcTriggerGetLevel(long lChannelNo, DWORD* dwpLevel);
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetFreq(long lChannelNo, DWORD dwFreqency);
typedef DWORD    PASCAL EXPORT funcAxcTriggerGetFreq(long lChannelNo, DWORD* dwpFreqency);	
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetEnable(long lChannelNo, DWORD dwUsage);
typedef DWORD    PASCAL EXPORT funcAxcTriggerGetEnable(long lChannelNo, DWORD* dwpUsage);
typedef DWORD    PASCAL EXPORT funcAxcTriggerReadAbsRamData(long lChannelNo, DWORD dwAddr, DWORD* dwpData);
typedef DWORD    PASCAL EXPORT funcAxcTriggerWriteAbsRamData(long lChannelNo, DWORD dwAddr, DWORD dwData);
typedef DWORD    PASCAL EXPORT funcAxcTriggerSetAbs(long lChannelNo, DWORD dwTrigNum, DWORD* dwTrigPos, DWORD dwDirection);

extern funcAxcInfoIsCNTModule                           *AxcInfoIsCNTModule;
extern funcAxcInfoGetModuleNo                           *AxcInfoGetModuleNo;
extern funcAxcInfoGetModuleCount                        *AxcInfoGetModuleCount;
extern funcAxcInfoGetChannelCount                       *AxcInfoGetChannelCount;
extern funcAxcInfoGetModule                             *AxcInfoGetModule;
extern funcAxcInfoGetModuleStatus                       *AxcInfoGetModuleStatus;
extern funcAxcInfoGetTotalChannelCount                  *AxcInfoGetTotalChannelCount;
extern funcAxcInfoGetFirstChannelNoOfModuleNo           *AxcInfoGetFirstChannelNoOfModuleNo;
extern funcAxcSignalSetEncInputMethod                   *AxcSignalSetEncInputMethod;
extern funcAxcSignalGetEncInputMethod                   *AxcSignalGetEncInputMethod;
extern funcAxcSignalSetCaptureFunction                  *AxcSignalSetCaptureFunction;
extern funcAxcSignalGetCaptureFunction                  *AxcSignalGetCaptureFunction;
extern funcAxcSignalGetCapturePos                       *AxcSignalGetCapturePos;
extern funcAxcSignalSetEncReverse                       *AxcSignalSetEncReverse;
extern funcAxcSignalGetEncReverse                       *AxcSignalGetEncReverse;
extern funcAxcSignalSetEncSource                        *AxcSignalSetEncSource;
extern funcAxcSignalGetEncSource                        *AxcSignalGetEncSource;
extern funcAxcSignalWriteOutput                         *AxcSignalWriteOutput;
extern funcAxcSignalReadOutput                          *AxcSignalReadOutput;
extern funcAxcSignalWriteOutputBit                      *AxcSignalWriteOutputBit;
extern funcAxcSignalReadOutputBit                       *AxcSignalReadOutputBit;
extern funcAxcSignalReadInput                           *AxcSignalReadInput;
extern funcAxcSignalReadInputBit                        *AxcSignalReadInputBit;
extern funcAxcMotSetMoveUnitPerPulse                    *AxcMotSetMoveUnitPerPulse;
extern funcAxcMotGetMoveUnitPerPulse                    *AxcMotGetMoveUnitPerPulse;
extern funcAxcStatusGetActPos                           *AxcStatusGetActPos;
extern funcAxcStatusSetActPos                           *AxcStatusSetActPos;
extern funcAxcStatusGetChannel                          *AxcStatusGetChannel;
extern funcAxcTriggerSetFunction                        *AxcTriggerSetFunction;
extern funcAxcTriggerGetFunction                        *AxcTriggerGetFunction;
extern funcAxcTriggerSetNotchPos                        *AxcTriggerSetNotchPos;
extern funcAxcTriggerGetNotchPos                        *AxcTriggerGetNotchPos;
extern funcAxcTriggerSetOutput                          *AxcTriggerSetOutput;
extern funcAxcTriggerSetNotchPos                        *AxcTriggerSetNotchPos;
extern funcAxcTriggerGetNotchPos                        *AxcTriggerGetNotchPos;
extern funcAxcTriggerSetBlockLowerPos                   *AxcTriggerSetBlockLowerPos;
extern funcAxcTriggerGetBlockLowerPos                   *AxcTriggerGetBlockLowerPos;
extern funcAxcTriggerSetBlockUpperPos                   *AxcTriggerSetBlockUpperPos;
extern funcAxcTriggerGetBlockUpperPos                   *AxcTriggerGetBlockUpperPos;
extern funcAxcTriggerSetPosPeriod                       *AxcTriggerSetPosPeriod;
extern funcAxcTriggerGetPosPeriod                       *AxcTriggerGetPosPeriod;
extern funcAxcTriggerSetDirectionCheck                  *AxcTriggerSetDirectionCheck;
extern funcAxcTriggerGetDirectionCheck                  *AxcTriggerGetDirectionCheck;
extern funcAxcTriggerSetBlock                           *AxcTriggerSetBlock;
extern funcAxcTriggerGetBlock                           *AxcTriggerGetBlock;
extern funcAxcTriggerSetTime                            *AxcTriggerSetTime;
extern funcAxcTriggerGetTime                            *AxcTriggerGetTime;
extern funcAxcTriggerSetLevel                           *AxcTriggerSetLevel;
extern funcAxcTriggerGetLevel                           *AxcTriggerGetLevel;
extern funcAxcTriggerSetFreq                            *AxcTriggerSetFreq;
extern funcAxcTriggerGetFreq                            *AxcTriggerGetFreq;
extern funcAxcTriggerSetEnable                          *AxcTriggerSetEnable;
extern funcAxcTriggerGetEnable                          *AxcTriggerGetEnable;
extern funcAxcTriggerReadAbsRamData                     *AxcTriggerReadAbsRamData;
extern funcAxcTriggerWriteAbsRamData                    *AxcTriggerWriteAbsRamData;
extern funcAxcTriggerSetAbs                             *AxcTriggerSetAbs;

BOOL LoadAXC();
BOOL FreeAXC();

#endif    __AXT_DAXC_H__