#ifndef __AXT_DAXD_H__
#define __AXT_DAXD_H__

//#include "AXHS.h"
#include "../../AXL(Library)/C, C++/AXHS.h"

typedef DWORD    PASCAL EXPORT funcAxdInfoIsDIOModule(DWORD *upStatus);
typedef DWORD    PASCAL EXPORT funcAxdInfoGetModuleNo(long lBoardNo, long lModulePos, long *lpModuleNo);
typedef DWORD    PASCAL EXPORT funcAxdInfoGetModuleCount(long *lpModuleCount);
typedef DWORD    PASCAL EXPORT funcAxdInfoGetInputCount(long lModuleNo, long *lpCount);
typedef DWORD    PASCAL EXPORT funcAxdInfoGetOutputCount(long lModuleNo, long *lpCount);
typedef DWORD    PASCAL EXPORT funcAxdInfoGetModule(long lModuleNo, long *lpBoardNo, long *lpModulePos, DWORD *upModuleID);
typedef DWORD    PASCAL EXPORT funcAxdInfoGetModuleStatus(long lModuleNo);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptSetModule(long lModuleNo, HWND hWnd, DWORD uMessage, AXT_INTERRUPT_PROC pProc, HANDLE *pEvent);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptSetModuleEnable(long lModuleNo, DWORD uUse);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptGetModuleEnable(long lModuleNo, DWORD *upUse);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptRead(long *lpModuleNo, DWORD *upFlag);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptEdgeSetBit(long lModuleNo, long lOffset, DWORD uMode, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptEdgeSetByte(long lModuleNo, long lOffset, DWORD uMode, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptEdgeSetWord(long lModuleNo, long lOffset, DWORD uMode, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptEdgeSetDword(long lModuleNo, long lOffset, DWORD uMode, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptEdgeGetBit(long lModuleNo, long lOffset, DWORD uMode, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptEdgeGetByte(long lModuleNo, long lOffset, DWORD uMode, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptEdgeGetWord(long lModuleNo, long lOffset, DWORD uMode, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptEdgeGetDword(long lModuleNo, long lOffset, DWORD uMode, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptEdgeSet(long lOffset, DWORD uMode, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdiInterruptEdgeGet(long lOffset, DWORD uMode, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdiLevelSetInportBit(long lModuleNo, long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdiLevelSetInportByte(long lModuleNo, long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdiLevelSetInportWord(long lModuleNo, long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdiLevelSetInportDword(long lModuleNo, long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdiLevelGetInportBit(long lModuleNo, long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdiLevelGetInportByte(long lModuleNo, long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdiLevelGetInportWord(long lModuleNo, long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdiLevelGetInportDword(long lModuleNo, long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdiLevelSetInport(long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdiLevelGetInport(long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdoLevelSetOutportBit(long lModuleNo, long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdoLevelSetOutportByte(long lModuleNo, long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdoLevelSetOutportWord(long lModuleNo, long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdoLevelSetOutportDword(long lModuleNo, long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdoLevelGetOutportBit(long lModuleNo, long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdoLevelGetOutportByte(long lModuleNo, long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdoLevelGetOutportWord(long lModuleNo, long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdoLevelGetOutportDword(long lModuleNo, long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdoLevelSetOutport(long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdoLevelGetOutport(long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdoWriteOutport(long lOffset, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdoWriteOutportBit(long lModuleNo, long lOffset, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdoWriteOutportByte(long lModuleNo, long lOffset, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdoWriteOutportWord(long lModuleNo, long lOffset, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdoWriteOutportDword(long lModuleNo, long lOffset, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdoReadOutport(long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdoReadOutportBit(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdoReadOutportByte(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdoReadOutportWord(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdoReadOutportDword(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdiReadInport(long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdiReadInportBit(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdiReadInportByte(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdiReadInportWord(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdiReadInportDword(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdReadExtInportBit(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdReadExtInportByte(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdReadExtInportWord(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdReadExtInportDword(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdReadExtOutportBit(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdReadExtOutportByte(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdReadExtOutportWord(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdReadExtOutportDword(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdWriteExtOutportBit(long lModuleNo, long lOffset, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdWriteExtOutportByte(long lModuleNo, long lOffset, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdWriteExtOutportWord(long lModuleNo, long lOffset, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdWriteExtOutportDword(long lModuleNo, long lOffset, DWORD uValue);
typedef DWORD    PASCAL EXPORT funcAxdLevelSetExtportBit(long lModuleNo, long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdLevelSetExtportByte(long lModuleNo, long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdLevelSetExtportWord(long lModuleNo, long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdLevelSetExtportDWord(long lModuleNo, long lOffset, DWORD uLevel);
typedef DWORD    PASCAL EXPORT funcAxdLevelGetExtportBit(long lModuleNo, long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdLevelGetExtportByte(long lModuleNo, long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdLevelGetExtportWord(long lModuleNo, long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdLevelGetExtportDword(long lModuleNo, long lOffset, DWORD *upLevel);
typedef DWORD    PASCAL EXPORT funcAxdiIsPulseOn(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdiIsPulseOff(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD    PASCAL EXPORT funcAxdiIsOn(long lModuleNo, long lOffset, long lCount, DWORD *upValue, long lStart);
typedef DWORD    PASCAL EXPORT funcAxdiIsOff(long lModuleNo, long lOffset, long lCount, DWORD *upValue, long lStart);
typedef DWORD    PASCAL EXPORT funcAxdoOutPulseOn(long lModuleNo, long lOffset, long lmSec);
typedef DWORD    PASCAL EXPORT funcAxdoOutPulseOff(long lModuleNo, long lOffset, long lmSec);
typedef DWORD    PASCAL EXPORT funcAxdoToggleStart(long lModuleNo, long lOffset, long lInitState, long lmSecOn, long lmSecOff, long lCount);
typedef DWORD    PASCAL EXPORT funcAxdoToggleStop(long lModuleNo, long lOffset, DWORD uOnOff);
typedef DWORD    PASCAL EXPORT funcAxdoSetNetworkErrorAct(long lModuleNo, DWORD dwSize, DWORD* dwaSetValue);
typedef DWORD    PASCAL EXPORT funcAxdSetContactNum(long lModuleNo, DWORD dwInputNum, DWORD dwOutputNum);
typedef DWORD    PASCAL EXPORT funcAxdGetContactNum(long lModuleNo, DWORD* dwpInputNum, DWORD* dwpOutputNum);
//---------------------------------------------------------//
extern    funcAxdInfoIsDIOModule              *AxdInfoIsDIOModule;
extern    funcAxdInfoGetModuleNo              *AxdInfoGetModuleNo;
extern    funcAxdInfoGetModuleCount           *AxdInfoGetModuleCount;
extern    funcAxdInfoGetInputCount            *AxdInfoGetInputCount;
extern    funcAxdInfoGetOutputCount           *AxdInfoGetOutputCount;
extern    funcAxdInfoGetModule                *AxdInfoGetModule;
extern    funcAxdInfoGetModuleStatus          *AxdInfoGetModuleStatus;
extern    funcAxdiInterruptSetModule          *AxdiInterruptSetModule;
extern    funcAxdiInterruptSetModuleEnable    *AxdiInterruptSetModuleEnable;
extern    funcAxdiInterruptGetModuleEnable    *AxdiInterruptGetModuleEnable;
extern    funcAxdiInterruptRead               *AxdiInterruptRead;
extern    funcAxdiInterruptEdgeSetBit         *AxdiInterruptEdgeSetBit;
extern    funcAxdiInterruptEdgeSetByte        *AxdiInterruptEdgeSetByte;
extern    funcAxdiInterruptEdgeSetWord        *AxdiInterruptEdgeSetWord;
extern    funcAxdiInterruptEdgeSetDword       *AxdiInterruptEdgeSetDword;
extern    funcAxdiInterruptEdgeGetBit         *AxdiInterruptEdgeGetBit;
extern    funcAxdiInterruptEdgeGetByte        *AxdiInterruptEdgeGetByte;
extern    funcAxdiInterruptEdgeGetWord        *AxdiInterruptEdgeGetWord;
extern    funcAxdiInterruptEdgeGetDword       *AxdiInterruptEdgeGetDword;
extern    funcAxdiInterruptEdgeSet            *AxdiInterruptEdgeSet;
extern    funcAxdiInterruptEdgeGet            *AxdiInterruptEdgeGet;
extern    funcAxdiLevelSetInportBit           *AxdiLevelSetInportBit;
extern    funcAxdiLevelSetInportByte          *AxdiLevelSetInportByte;
extern    funcAxdiLevelSetInportWord          *AxdiLevelSetInportWord;
extern    funcAxdiLevelSetInportDword         *AxdiLevelSetInportDword;
extern    funcAxdiLevelGetInportBit           *AxdiLevelGetInportBit;
extern    funcAxdiLevelGetInportByte          *AxdiLevelGetInportByte;
extern    funcAxdiLevelGetInportWord          *AxdiLevelGetInportWord;
extern    funcAxdiLevelGetInportDword         *AxdiLevelGetInportDword;
extern    funcAxdiLevelSetInport              *AxdiLevelSetInport;
extern    funcAxdiLevelGetInport              *AxdiLevelGetInport;
extern    funcAxdoLevelSetOutportBit          *AxdoLevelSetOutportBit;
extern    funcAxdoLevelSetOutportByte         *AxdoLevelSetOutportByte;
extern    funcAxdoLevelSetOutportWord         *AxdoLevelSetOutportWord;
extern    funcAxdoLevelSetOutportDword        *AxdoLevelSetOutportDword;
extern    funcAxdoLevelGetOutportBit          *AxdoLevelGetOutportBit;
extern    funcAxdoLevelGetOutportByte         *AxdoLevelGetOutportByte;
extern    funcAxdoLevelGetOutportWord         *AxdoLevelGetOutportWord;
extern    funcAxdoLevelGetOutportDword        *AxdoLevelGetOutportDword;
extern    funcAxdoLevelSetOutport             *AxdoLevelSetOutport;
extern    funcAxdoLevelGetOutport             *AxdoLevelGetOutport;
extern    funcAxdoWriteOutport                *AxdoWriteOutport;
extern    funcAxdoWriteOutportBit             *AxdoWriteOutportBit;
extern    funcAxdoWriteOutportByte            *AxdoWriteOutportByte;
extern    funcAxdoWriteOutportWord            *AxdoWriteOutportWord;
extern    funcAxdoWriteOutportDword           *AxdoWriteOutportDword;
extern    funcAxdoReadOutport                 *AxdoReadOutport;
extern    funcAxdoReadOutportBit              *AxdoReadOutportBit;
extern    funcAxdoReadOutportByte             *AxdoReadOutportByte;
extern    funcAxdoReadOutportWord             *AxdoReadOutportWord;
extern    funcAxdoReadOutportDword            *AxdoReadOutportDword;
extern    funcAxdiReadInport                  *AxdiReadInport;
extern    funcAxdiReadInportBit               *AxdiReadInportBit;
extern    funcAxdiReadInportByte              *AxdiReadInportByte;
extern    funcAxdiReadInportWord              *AxdiReadInportWord;
extern    funcAxdiReadInportDword             *AxdiReadInportDword;
extern    funcAxdReadExtInportBit             *AxdReadExtInportBit;
extern    funcAxdReadExtInportByte            *AxdReadExtInportByte;
extern    funcAxdReadExtInportWord            *AxdReadExtInportWord;
extern    funcAxdReadExtInportDword           *AxdReadExtInportDword;
extern    funcAxdReadExtOutportBit            *AxdReadExtOutportBit;
extern    funcAxdReadExtOutportByte           *AxdReadExtOutportByte;
extern    funcAxdReadExtOutportWord           *AxdReadExtOutportWord;
extern    funcAxdReadExtOutportDword          *AxdReadExtOutportDword;
extern    funcAxdWriteExtOutportBit           *AxdWriteExtOutportBit;
extern    funcAxdWriteExtOutportByte          *AxdWriteExtOutportByte;
extern    funcAxdWriteExtOutportWord          *AxdWriteExtOutportWord;
extern    funcAxdWriteExtOutportDword         *AxdWriteExtOutportDword;
extern    funcAxdLevelSetExtportBit           *AxdLevelSetExtportBit;
extern    funcAxdLevelSetExtportByte          *AxdLevelSetExtportByte;
extern    funcAxdLevelSetExtportWord          *AxdLevelSetExtportWord;
extern    funcAxdLevelSetExtportDWord         *AxdLevelSetExtportDWord;
extern    funcAxdLevelGetExtportBit	          *AxdLevelGetExtportBit;
extern    funcAxdLevelGetExtportByte          *AxdLevelGetExtportByte;
extern    funcAxdLevelGetExtportWord          *AxdLevelGetExtportWord;
extern    funcAxdLevelGetExtportDword         *AxdLevelGetExtportDword;
extern    funcAxdiIsPulseOn                   *AxdiIsPulseOn;
extern    funcAxdiIsPulseOff                  *AxdiIsPulseOff;
extern    funcAxdiIsOn                        *AxdiIsOn;
extern    funcAxdiIsOff                       *AxdiIsOff;
extern    funcAxdoOutPulseOn                  *AxdoOutPulseOn;
extern    funcAxdoOutPulseOff                 *AxdoOutPulseOff;
extern    funcAxdoToggleStart                 *AxdoToggleStart;
extern    funcAxdoToggleStop                  *AxdoToggleStop;
extern    funcAxdoSetNetworkErrorAct          *AxdoSetNetworkErrorAct;
extern    funcAxdSetContactNum                *AxdSetContactNum;
extern    funcAxdGetContactNum                *AxdGetContactNum;

BOOL LoadAXD();
BOOL FreeAXD();

#endif    __AXT_DAXD_H__
