#ifndef __AXT_DAXDEV_H__
#define __AXT_DAXDEV_H__

//#include "AXHD.h"
#include "../../AXL(Library)/C, C++/AXHS.h"
#include "../../AXL(Library)/C, C++/AXHD.h"

typedef DWORD   PASCAL EXPORT funcAxlGetBoardAddress(long lBoardNo, DWORD *upBoardAddress);
typedef DWORD   PASCAL EXPORT funcAxlGetBoardID(long lBoardNo, DWORD *upBoardID);
typedef DWORD   PASCAL EXPORT funcAxlGetBoardVersion(long lBoardNo, DWORD *upBoardVersion);
typedef DWORD   PASCAL EXPORT funcAxlGetModuleID(long lBoardNo, long lModulePos, DWORD *upModuleID);
typedef DWORD   PASCAL EXPORT funcAxlGetModuleVersion(long lBoardNo, long lModulePos, DWORD *upModuleVersion);
typedef DWORD   PASCAL EXPORT funcAxlGetModuleNodeInfo(long lBoardNo, long lModulePos, long *upNetNo, DWORD *upNodeAddr);

typedef DWORD   PASCAL EXPORT funcAxlSetDataFlash(long lBoardNo, long lPageAddr, long lBytesNum, BYTE *bpSetData);
typedef DWORD   PASCAL EXPORT funcAxlGetDataFlash(long lBoardNo, long lPageAddr, long lBytesNum, BYTE *bpGetData);

typedef DWORD   PASCAL EXPORT funcAxaInfoGetModuleNo(long lBoardNo, long lModulePos, long *lpModuleNo);
typedef DWORD   PASCAL EXPORT funcAxdInfoGetModuleNo(long lBoardNo, long lModulePos, long *lpModuleNo);
typedef DWORD   PASCAL EXPORT funcAxmSetCommand(long lAxisNo, IPCOMMAND sCommand);
typedef DWORD   PASCAL EXPORT funcAxmSetCommandData08(long lAxisNo, IPCOMMAND sCommand, DWORD uData);
typedef DWORD   PASCAL EXPORT funcAxmGetCommandData08(long lAxisNo, IPCOMMAND sCommand, DWORD *upData);
typedef DWORD   PASCAL EXPORT funcAxmSetCommandData16(long lAxisNo, IPCOMMAND sCommand, DWORD uData);
typedef DWORD   PASCAL EXPORT funcAxmGetCommandData16(long lAxisNo, IPCOMMAND sCommand, DWORD *upData);
typedef DWORD   PASCAL EXPORT funcAxmSetCommandData24(long lAxisNo, IPCOMMAND sCommand, DWORD uData);
typedef DWORD   PASCAL EXPORT funcAxmGetCommandData24(long lAxisNo, IPCOMMAND sCommand, DWORD *upData);
typedef DWORD   PASCAL EXPORT funcAxmSetCommandData32(long lAxisNo, IPCOMMAND sCommand, DWORD uData);
typedef DWORD   PASCAL EXPORT funcAxmGetCommandData32(long lAxisNo, IPCOMMAND sCommand, DWORD *upData);
typedef DWORD   PASCAL EXPORT funcAxmSetCommandQi(long lAxisNo, QICOMMAND sCommand);
typedef DWORD   PASCAL EXPORT funcAxmSetCommandData08Qi(long lAxisNo, QICOMMAND sCommand, DWORD uData);
typedef DWORD   PASCAL EXPORT funcAxmGetCommandData08Qi(long lAxisNo, QICOMMAND sCommand, DWORD *upData);
typedef DWORD   PASCAL EXPORT funcAxmSetCommandData16Qi(long lAxisNo, QICOMMAND sCommand, DWORD uData);
typedef DWORD   PASCAL EXPORT funcAxmGetCommandData16Qi(long lAxisNo, QICOMMAND sCommand, DWORD *upData);
typedef DWORD   PASCAL EXPORT funcAxmSetCommandData24Qi(long lAxisNo, QICOMMAND sCommand, DWORD uData);
typedef DWORD   PASCAL EXPORT funcAxmGetCommandData24Qi(long lAxisNo, QICOMMAND sCommand, DWORD *upData);
typedef DWORD   PASCAL EXPORT funcAxmSetCommandData32Qi(long lAxisNo, QICOMMAND sCommand, DWORD uData);
typedef DWORD   PASCAL EXPORT funcAxmGetCommandData32Qi(long lAxisNo, QICOMMAND sCommand, DWORD *upData);
typedef DWORD   PASCAL EXPORT funcAxmGetPortData(long lAxisNo, WORD wOffset, DWORD *upData);
typedef DWORD   PASCAL EXPORT funcAxmSetPortData(long lAxisNo, WORD wOffset, DWORD dwData);
typedef DWORD   PASCAL EXPORT funcAxmGetPortDataQi(long lAxisNo, WORD wOffset, WORD *upData);
typedef DWORD   PASCAL EXPORT funcAxmSetPortDataQi(long lAxisNo, WORD wOffset, WORD dwData);
typedef DWORD   PASCAL EXPORT funcAxmSetScriptCaptionIp(long lAxisNo, long sc, DWORD event, DWORD data);
typedef DWORD   PASCAL EXPORT funcAxmGetScriptCaptionIp(long lAxisNo, long sc, DWORD event, DWORD data);
typedef DWORD   PASCAL EXPORT funcAxmSetScriptCaptionQi(long lAxisNo, long sc, DWORD event, DWORD cmd, DWORD data);
typedef DWORD   PASCAL EXPORT funcAxmGetScriptCaptionQi(long lAxisNo, long sc, DWORD *event, DWORD *cmd, DWORD *data);
typedef DWORD   PASCAL EXPORT funcAxmSetScriptCaptionQueueClear(long lAxisNo, DWORD uSelect);
typedef DWORD   PASCAL EXPORT funcAxmGetScriptCaptionQueueCount(long lAxisNo, DWORD *updata, DWORD uSelect);
typedef DWORD   PASCAL EXPORT funcAxmGetScriptCaptionQueueDataCount(long lAxisNo, DWORD *updata, DWORD uSelect);
typedef DWORD   PASCAL EXPORT funcAxmGetOptimizeDriveData(long lAxisNo, double dMinVel, double dVel, double dAccel, double  dDecel, WORD *wRangeData, WORD *wStartStopSpeedData, WORD *wObjectSpeedData, WORD *wAccelRate, WORD *wDecelRate);
typedef DWORD   PASCAL EXPORT funcAxmBoardWriteByte(long lBoardNo, WORD wOffset, BYTE byData);
typedef DWORD   PASCAL EXPORT funcAxmBoardReadByte(long lBoardNo, WORD wOffset, BYTE *byData);
typedef DWORD   PASCAL EXPORT funcAxmBoardWriteWord(long lBoardNo, WORD wOffset, WORD wData);
typedef DWORD   PASCAL EXPORT funcAxmBoardReadWord(long lBoardNo, WORD wOffset, WORD *wData);
typedef DWORD   PASCAL EXPORT funcAxmBoardWriteDWord(long lBoardNo, WORD wOffset, DWORD dwData);
typedef DWORD   PASCAL EXPORT funcAxmBoardReadDWord(long lBoardNo, WORD wOffset, DWORD *dwData);
typedef DWORD   PASCAL EXPORT funcAxmModuleWriteByte(long lBoardNo, long lModulePos, WORD wOffset, BYTE byData);
typedef DWORD   PASCAL EXPORT funcAxmModuleReadByte(long lBoardNo, long lModulePos, WORD wOffset, BYTE *byData);
typedef DWORD   PASCAL EXPORT funcAxmModuleWriteWord(long lBoardNo, long lModulePos, WORD wOffset, WORD wData);
typedef DWORD   PASCAL EXPORT funcAxmModuleReadWord(long lBoardNo, long lModulePos, WORD wOffset, WORD *wData);
typedef DWORD   PASCAL EXPORT funcAxmModuleWriteDWord(long lBoardNo, long lModulePos, WORD wOffset, DWORD dwData);
typedef DWORD   PASCAL EXPORT funcAxmModuleReadDWord(long lBoardNo, long lModulePos, WORD wOffset, DWORD *dwData);
typedef DWORD   PASCAL EXPORT funcAxmStatusSetActComparatorPos(long lAxisNo, double dPos);
typedef DWORD   PASCAL EXPORT funcAxmStatusGetActComparatorPos(long lAxisNo, double *dpPos);
typedef DWORD   PASCAL EXPORT funcAxmStatusSetCmdComparatorPos(long lAxisNo, double dPos);
typedef DWORD   PASCAL EXPORT funcAxmStatusGetCmdComparatorPos(long lAxisNo, double *dpPos);
typedef DWORD   PASCAL EXPORT funcAxmLineMoveVel(long lCoord, double dVel, double dAccel, double dDecel);
typedef DWORD   PASCAL EXPORT funcAxmSensorSetSignal(long lAxisNo, DWORD uLevel);
typedef DWORD   PASCAL EXPORT funcAxmSensorGetSignal(long lAxisNo, DWORD *upLevel);
typedef DWORD   PASCAL EXPORT funcAxmSensorReadSignal(long lAxisNo, DWORD *upStatus);
typedef DWORD   PASCAL EXPORT funcAxmSensorMovePos(long lAxisNo, double dPos, double dVel, double dAccel, double dDecel, long lMethod);
typedef DWORD   PASCAL EXPORT funcAxmSensorStartMovePos(long lAxisNo, double dPos, double dVel, double dAccel, double dDecel, long lMethod);
typedef DWORD   PASCAL EXPORT funcAxmHomeGetStepTrace(long lAxisNo, long *lpStepCount, DWORD *upMainStepNumber, DWORD *upStepNumber, DWORD *upStepBranch);
typedef DWORD   PASCAL EXPORT funcAxmHomeSetConfig(long lAxisNo, DWORD uZphasCount, long lHomeMode, long lClearSet, double dOrgVel, double dLastVel, double dLeavePos);
typedef DWORD   PASCAL EXPORT funcAxmHomeGetConfig(long lAxisNo, DWORD *upZphasCount, long *lpHomeMode, long *lpClearSet, double *dpOrgVel, double *dpLastVel, double *dpLeavePos); //KKJ(070215)
typedef DWORD   PASCAL EXPORT funcAxmHomeSetMoveSearch(long lAxisNo, double dVel, double dAccel, double dDecel);
typedef DWORD   PASCAL EXPORT funcAxmHomeSetMoveReturn(long lAxisNo, double dVel, double dAccel, double dDecel);
typedef DWORD   PASCAL EXPORT funcAxmHomeSetMoveLeave(long lAxisNo, double dVel, double dAccel, double dDecel);
typedef DWORD   PASCAL EXPORT funcAxmHomeSetMultiMoveSearch(long lArraySize, long *lpAxesNo, double *dpVel, double *dpAccel, double *dpDecel);
typedef DWORD   PASCAL EXPORT funcAxmContiSetProfileMode(long lCoord, DWORD uProfileMode);
typedef DWORD   PASCAL EXPORT funcAxmContiGetProfileMode(long lCoord, DWORD *upProfileMode);
typedef DWORD   PASCAL EXPORT funcAxmMoveProfilePos(long lAxisNo, long lProfileSize, double *dpPos, double *dpMinVel, double *dpVel, double *dpAccel, double *dpDecel);
typedef DWORD   PASCAL EXPORT funcAxmLogSetAxis(long lAxisNo, DWORD uUse);
typedef DWORD   PASCAL EXPORT funcAxmLogGetAxis(long lAxisNo, DWORD *upUse);
typedef DWORD   PASCAL EXPORT funcAxdiInterruptFlagReadBit(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD   PASCAL EXPORT funcAxdiInterruptFlagReadByte(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD   PASCAL EXPORT funcAxdiInterruptFlagReadWord(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD   PASCAL EXPORT funcAxdiInterruptFlagReadDword(long lModuleNo, long lOffset, DWORD *upValue);
typedef DWORD   PASCAL EXPORT funcAxdiInterruptFlagRead(long lOffset, DWORD *upValue);
typedef DWORD   PASCAL EXPORT funcAxdLogSetModule(long lModuleNo, DWORD uUse);
typedef DWORD   PASCAL EXPORT funcAxdLogGetModule(long lModuleNo, DWORD *upUse);
typedef DWORD   PASCAL EXPORT funcAxaiLogSetChannel(long lChannelNo, DWORD uUse);
typedef DWORD   PASCAL EXPORT funcAxaiLogGetChannel(long lChannelNo, DWORD *upUse);
typedef DWORD   PASCAL EXPORT funcAxaoLogSetChannel(long lChannelNo, DWORD uUse);
typedef DWORD   PASCAL EXPORT funcAxaoLogGetChannel(long lChannelNo, DWORD *upUse);
typedef DWORD   PASCAL EXPORT funcAxlGetFirmwareVersion(long lBoardNo, PTCHAR szVersion);
typedef DWORD   PASCAL EXPORT funcAxlSetFirmwareCopy(long lBoardNo, WORD *wData, WORD *wCmdData);
typedef DWORD   PASCAL EXPORT funcAxlSetFirmwareUpdate(long lBoardNo);
typedef DWORD   PASCAL EXPORT funcAxlCheckStatus(long lBoardNo, DWORD* dwStatus);
typedef DWORD   PASCAL EXPORT funcAxlRtexUniversalCmd(long lBoardNo, WORD wCmd, WORD wOffset, WORD *wData);
typedef DWORD   PASCAL EXPORT funcAxmRtexSlaveCmd(long lAxisNo, DWORD dwCmdCode, DWORD dwTypeCode, DWORD dwIndexCode, DWORD dwCmdConfigure, DWORD dwValue);
typedef DWORD   PASCAL EXPORT funcAxmRtexGetSlaveCmdResult(long lAxisNo, DWORD* dwIndex, DWORD *dwValue);
typedef DWORD   PASCAL EXPORT funcAxmRtexGetAxisStatus(long lAxisNo, DWORD *dwStatus);
typedef DWORD   PASCAL EXPORT funcAxmRtexGetAxisReturnData(long lAxisNo,  DWORD *dwReturn1, DWORD *dwReturn2, DWORD *dwReturn3);
typedef DWORD   PASCAL EXPORT funcAxmRtexGetAxisSlaveStatus(long lAxisNo,  DWORD *dwStatus);

typedef DWORD   PASCAL EXPORT funcAxmSetAxisCmd(long lAxisNo, DWORD* tagCommand);
typedef DWORD   PASCAL EXPORT funcAxmGetAxisCmdResult(long lAxisNo, DWORD* tagCommand);
typedef DWORD   PASCAL EXPORT funcAxlGetDpRamData(long lBoardNo, WORD wAddress, DWORD* dwpRdData);
typedef DWORD   PASCAL EXPORT funcAxlBoardReadDpramWord(long lBoardNo, WORD wOffset, DWORD* dwpRdData);
typedef DWORD   PASCAL EXPORT funcAxlSetSendBoardCommand(long lBoardNo, DWORD dwCommand, DWORD* dwpSendData, DWORD dwLength);
typedef DWORD   PASCAL EXPORT funcAxlGetResponseBoardCommand(long lBoardNo, DWORD* dwpReadData);
typedef DWORD   PASCAL EXPORT funcAxmInfoGetFirmwareVersion(long lAxisNo, unsigned char* ucaFirmwareVersion);
typedef DWORD   PASCAL EXPORT funcAxaInfoGetFirmwareVersion(long lModuleNo, unsigned char* ucaFirmwareVersion);
typedef DWORD   PASCAL EXPORT funcAxdInfoGetFirmwareVersion(long lModuleNo, unsigned char* ucaFirmwareVersion);
typedef DWORD   PASCAL EXPORT funcAxmSetTorqFeedForward(long lAxisNo, DWORD dwTorqFeedForward);
typedef DWORD   PASCAL EXPORT funcAxmGetTorqFeedForward(long lAxisNo, DWORD* dwpTorqFeedForward);
typedef DWORD   PASCAL EXPORT funcAxmSetVelocityFeedForward(long lAxisNo, DWORD dwVelocityFeedForward);
typedef DWORD   PASCAL EXPORT funcAxmGetVelocityFeedForward(long lAxisNo, DWORD* dwpVelocityFeedForward);

typedef DWORD   PASCAL EXPORT funcAxmSignalSetEncoderType(long lAxisNo, DWORD dwEncoderType);
typedef DWORD   PASCAL EXPORT funcAxmSignalGetEncoderType(long lAxisNo, DWORD* dwpEncoderType);
typedef DWORD   PASCAL EXPORT funcAxmSetSendAxisCommand(long lAxisNo, WORD wCommand, WORD* wpSendData, WORD wLength);

typedef DWORD   PASCAL EXPORT funcAxmMotSetUserMotion(long lAxisNo, double dVelocity, double dAccel, double dDecel);
typedef DWORD   PASCAL EXPORT funcAxmMotSetUserMotionUsage(long lAxisNo, DWORD dwUsage);
typedef DWORD   PASCAL EXPORT funcAxmMotSetUserPosMotion(long lAxisNo, double dVelocity, double dAccel, double dDecel, double dLoadPos, double dUnLoadPos, DWORD dwFilter, DWORD dwDelay);
typedef DWORD   PASCAL EXPORT funcAxmMotSetUserPosMotionUsage(long lAxisNo, DWORD dwUsage);
typedef DWORD   PASCAL EXPORT funcAxcKeWriteRamDataAddr(long lChannelNo, DWORD dwAddr, DWORD dwData);
typedef DWORD   PASCAL EXPORT funcAxcKeReadRamDataAddr(long lChannelNo, DWORD dwAddr, DWORD* dwpData);
typedef DWORD   PASCAL EXPORT funcAxcKeResetRamDataAll(long lModuleNo, DWORD dwData);
typedef DWORD   PASCAL EXPORT funcAxcTriggerSetTimeout(long lChannelNo, DWORD dwTimeout);
typedef DWORD   PASCAL EXPORT funcAxcTriggerGetTimeout(long lChannelNo, DWORD* dwpTimeout);
typedef DWORD   PASCAL EXPORT funcAxcStatusGetWaitState(long lChannelNo, DWORD* dwpState);
typedef DWORD   PASCAL EXPORT funcAxcStatusSetWaitState(long lChannelNo, DWORD dwState);
typedef DWORD   PASCAL EXPORT funcAxmSeqSetAxisMap(long lSeqMapNo, long lSeqMapSize, long* lSeqAxesNo);
typedef DWORD   PASCAL EXPORT funcAxmSeqGetAxisMap(long lSeqMapNo, long* lSeqMapSize, long* lSeqAxesNo);
typedef DWORD   PASCAL EXPORT funcAxmSeqSetMasterAxisNo(long lSeqMapNo, long lMasterAxisNo);
typedef DWORD   PASCAL EXPORT funcAxmSeqBeginNode(long lSeqMapNo);
typedef DWORD   PASCAL EXPORT funcAxmSeqEndNode(long lSeqMapNo);
typedef DWORD   PASCAL EXPORT funcAxmSeqStart(long lSeqMapNo, DWORD dwStartOption);
typedef DWORD   PASCAL EXPORT funcAxmSeqAddNode(long lSeqMapNo, double* dPosition, double dVelocity, double dAcceleration, double dDeceleration, double dNextVelocity);
typedef DWORD   PASCAL EXPORT funcAxmSeqGetNodeNum(long lSeqMapNo, long* lCurNodeNo);
typedef DWORD   PASCAL EXPORT funcAxmSeqGetTotalNodeNum(long lSeqMapNo, long* lTotalNodeCnt);
typedef DWORD   PASCAL EXPORT funcAxmSeqIsMotion(long lSeqMapNo, DWORD* dwInMotion);
typedef DWORD   PASCAL EXPORT funcAxmSeqWriteClear(long lSeqMapNo);
typedef DWORD   PASCAL EXPORT funcAxmSeqStop(long lSeqMapNo, DWORD dwStopMode);

//---------------------------------------------------------//
extern funcAxlGetBoardAddress                   *AxlGetBoardAddress;
extern funcAxlGetBoardID                        *AxlGetBoardID;
extern funcAxlGetBoardVersion                   *AxlGetBoardVersion;
extern funcAxlGetModuleID                       *AxlGetModuleID;
extern funcAxlGetModuleVersion                  *AxlGetModuleVersion;
extern funcAxlGetModuleNodeInfo                 *AxlGetModuleNodeInfo;

extern funcAxlSetDataFlash                      *AxlSetDataFlash;
extern funcAxlGetDataFlash                      *AxlGetDataFlash;

extern funcAxaInfoGetModuleNo                   *AxaGetInfoModuleNo;
extern funcAxdInfoGetModuleNo                   *AxdGetInfoModuleNo;
extern funcAxmSetCommand                        *AxmSetCommand;
extern funcAxmSetCommandData08                  *AxmSetCommandData08;
extern funcAxmGetCommandData08                  *AxmGetCommandData08;
extern funcAxmSetCommandData16                  *AxmSetCommandData16;
extern funcAxmGetCommandData16                  *AxmGetCommandData16;
extern funcAxmSetCommandData24                  *AxmSetCommandData24;
extern funcAxmGetCommandData24                  *AxmGetCommandData24;
extern funcAxmSetCommandData32                  *AxmSetCommandData32;
extern funcAxmGetCommandData32                  *AxmGetCommandData32;
extern funcAxmSetCommandQi                      *AxmSetCommandQi;
extern funcAxmSetCommandData08Qi                *AxmSetCommandData08Qi;
extern funcAxmGetCommandData08Qi                *AxmGetCommandData08Qi;
extern funcAxmSetCommandData16Qi                *AxmSetCommandData16Qi;
extern funcAxmGetCommandData16Qi                *AxmGetCommandData16Qi;
extern funcAxmSetCommandData24Qi                *AxmSetCommandData24Qi;
extern funcAxmGetCommandData24Qi                *AxmGetCommandData24Qi;
extern funcAxmSetCommandData32Qi                *AxmSetCommandData32Qi;
extern funcAxmGetCommandData32Qi                *AxmGetCommandData32Qi;
extern funcAxmGetPortData                       *AxmGetPortData;
extern funcAxmSetPortData                       *AxmSetPortData;
extern funcAxmGetPortDataQi                     *AxmGetPortDataQi;
extern funcAxmSetPortDataQi                     *AxmSetPortDataQi;
extern funcAxmSetScriptCaptionIp                *AxmSetScriptCaptionIp;
extern funcAxmGetScriptCaptionIp                *AxmGetScriptCaptionIp;
extern funcAxmSetScriptCaptionQi                *AxmSetScriptCaptionQi;
extern funcAxmGetScriptCaptionQi                *AxmGetScriptCaptionQi;
extern funcAxmSetScriptCaptionQueueClear        *AxmSetScriptCaptionQueueClear;
extern funcAxmGetScriptCaptionQueueCount        *AxmGetScriptCaptionQueueCount;
extern funcAxmGetScriptCaptionQueueDataCount    *AxmGetScriptCaptionQueueDataCount;
extern funcAxmGetOptimizeDriveData              *AxmGetOptimizeDriveData;
extern funcAxmBoardWriteByte                    *AxmBoardWriteByte;
extern funcAxmBoardReadByte                     *AxmBoardReadByte;
extern funcAxmBoardWriteWord                    *AxmBoardWriteWord;
extern funcAxmBoardReadWord                     *AxmBoardReadWord;
extern funcAxmBoardWriteDWord                   *AxmBoardWriteDWord;
extern funcAxmBoardReadDWord                    *AxmBoardReadDWord;
extern funcAxmModuleWriteByte                   *AxmModuleWriteByte;
extern funcAxmModuleReadByte                    *AxmModuleReadByte;
extern funcAxmModuleWriteWord                   *AxmModuleWriteWord;
extern funcAxmModuleReadWord                    *AxmModuleReadWord;
extern funcAxmModuleWriteDWord                  *AxmModuleWriteDWord;
extern funcAxmModuleReadDWord                   *AxmModuleReadDWord;
extern funcAxmStatusSetActComparatorPos         *AxmStatusSetActComparatorPos;
extern funcAxmStatusGetActComparatorPos         *AxmStatusGetActComparatorPos;
extern funcAxmStatusSetCmdComparatorPos         *AxmStatusSetCmdComparatorPos;
extern funcAxmStatusGetCmdComparatorPos         *AxmStatusGetCmdComparatorPos;
extern funcAxmLineMoveVel                       *AxmLineMoveVel;
extern funcAxmSensorSetSignal                   *AxmSensorSetSignal;
extern funcAxmSensorGetSignal                   *AxmSensorGetSignal;
extern funcAxmSensorReadSignal                  *AxmSensorReadSignal;
extern funcAxmSensorMovePos                     *AxmSensorMovePos;
extern funcAxmSensorStartMovePos                *AxmSensorStartMovePos;
extern funcAxmHomeGetStepTrace                  *AxmHomeGetStepTrace;
extern funcAxmHomeSetConfig                     *AxmHomeSetConfig;
extern funcAxmHomeGetConfig                     *AxmHomeGetConfig;
extern funcAxmHomeSetMoveSearch                 *AxmHomeSetMoveSearch;
extern funcAxmHomeSetMoveReturn                 *AxmHomeSetMoveReturn;
extern funcAxmHomeSetMoveLeave                  *AxmHomeSetMoveLeave;
extern funcAxmHomeSetMultiMoveSearch            *AxmHomeSetMultiMoveSearch;
extern funcAxmContiSetProfileMode               *AxmContiSetProfileMode;
extern funcAxmContiGetProfileMode               *AxmContiGetProfileMode;
extern funcAxmMoveProfilePos                    *AxmMoveProfilePos;
extern funcAxdiInterruptFlagReadBit             *AxdiInterruptFlagReadBit;
extern funcAxdiInterruptFlagReadByte            *AxdiInterruptFlagReadByte;
extern funcAxdiInterruptFlagReadWord            *AxdiInterruptFlagReadWord;
extern funcAxdiInterruptFlagReadDword           *AxdiInterruptFlagReadDword;
extern funcAxdiInterruptFlagRead                *AxdiInterruptFlagRead;
extern funcAxmLogSetAxis                        *AxmLogSetAxis;
extern funcAxmLogGetAxis                        *AxmLogGetAxis;
extern funcAxaiLogSetChannel                    *AxaiLogSetChannel;
extern funcAxaiLogGetChannel                    *AxaiLogGetChannel;
extern funcAxaoLogSetChannel                    *AxaoLogSetChannel;
extern funcAxaoLogGetChannel                    *AxaoLogGetChannel;
extern funcAxdLogSetModule                      *AxdLogSetModule;
extern funcAxdLogGetModule                      *AxdLogGetModule;
extern funcAxlGetFirmwareVersion                *AxlGetFirmwareVersion;
extern funcAxlSetFirmwareCopy                   *AxlSetFirmwareCopy;
extern funcAxlSetFirmwareUpdate                 *AxlSetFirmwareUpdate;
extern funcAxlCheckStatus                       *AxlCheckStatus;
extern funcAxlRtexUniversalCmd                  *AxlRtexUniversalCmd;
extern funcAxmRtexSlaveCmd                      *AxmRtexSlaveCmd;
extern funcAxmRtexGetSlaveCmdResult             *AxmRtexGetSlaveCmdResult;
extern funcAxmRtexGetAxisStatus                 *AxmRtexGetAxisStatus;
extern funcAxmRtexGetAxisReturnData             *AxmRtexGetAxisReturnData;
extern funcAxmRtexGetAxisSlaveStatus            *AxmRtexGetAxisSlaveStatus;

extern funcAxmSetAxisCmd                        *AxmSetAxisCmd;
extern funcAxmGetAxisCmdResult                  *AxmGetAxisCmdResult;
extern funcAxlGetDpRamData                      *AxlGetDpRamData;
extern funcAxlBoardReadDpramWord                *AxlBoardReadDpramWord;
extern funcAxlSetSendBoardCommand               *AxlSetSendBoardCommand;
extern funcAxlGetResponseBoardCommand           *AxlGetResponseBoardCommand;
extern funcAxmInfoGetFirmwareVersion            *AxmInfoGetFirmwareVersion;
extern funcAxaInfoGetFirmwareVersion            *AxaInfoGetFirmwareVersion;
extern funcAxdInfoGetFirmwareVersion            *AxdInfoGetFirmwareVersion;
extern funcAxmSetTorqFeedForward                *AxmSetTorqFeedForward;
extern funcAxmGetTorqFeedForward                *AxmGetTorqFeedForward;
extern funcAxmSetVelocityFeedForward            *AxmSetVelocityFeedForward;
extern funcAxmGetVelocityFeedForward            *AxmGetVelocityFeedForward;

extern funcAxmSignalSetEncoderType              *AxmSignalSetEncoderType;
extern funcAxmSignalGetEncoderType              *AxmSignalGetEncoderType;
extern funcAxmSetSendAxisCommand                *AxmSetSendAxisCommand;

extern funcAxmMotSetUserMotion                  *AxmMotSetUserMotion;
extern funcAxmMotSetUserMotionUsage             *AxmMotSetUserMotionUsage;
extern funcAxmMotSetUserPosMotion               *AxmMotSetUserPosMotion;
extern funcAxmMotSetUserPosMotionUsage          *AxmMotSetUserPosMotionUsage;
extern funcAxcKeWriteRamDataAddr                *AxcKeWriteRamDataAddr;
extern funcAxcKeReadRamDataAddr                 *AxcKeReadRamDataAddr;
extern funcAxcKeResetRamDataAll                 *AxcKeResetRamDataAll;
extern funcAxcTriggerSetTimeout                 *AxcTriggerSetTimeout;
extern funcAxcTriggerGetTimeout                 *AxcTriggerGetTimeout;
extern funcAxcStatusGetWaitState                *AxcStatusGetWaitState;
extern funcAxcStatusSetWaitState                *AxcStatusSetWaitState;
extern funcAxmSeqSetAxisMap                     *AxmSeqSetAxisMap;
extern funcAxmSeqGetAxisMap                     *AxmSeqGetAxisMap;
extern funcAxmSeqSetMasterAxisNo                *AxmSeqSetMasterAxisNo;
extern funcAxmSeqBeginNode                      *AxmSeqBeginNode;
extern funcAxmSeqEndNode                        *AxmSeqEndNode;
extern funcAxmSeqStart                          *AxmSeqStart;
extern funcAxmSeqAddNode                        *AxmSeqAddNode;
extern funcAxmSeqGetNodeNum                     *AxmSeqGetNodeNum;
extern funcAxmSeqGetTotalNodeNum                *AxmSeqGetTotalNodeNum;
extern funcAxmSeqIsMotion                       *AxmSeqIsMotion;
extern funcAxmSeqWriteClear                     *AxmSeqWriteClear;
extern funcAxmSeqStop                           *AxmSeqStop;

BOOL LoadAXDev();
BOOL FreeAXDev();

#endif    __AXT_DAXDEV_H__
